src/com/fwdekker/randomness/number/InsertRandomNumber.java, src/com/fwdekker/randomness/number/NumberSettings.java, src/com/fwdekker/randomness/number/NumberSettingsAction.java, src/com/fwdekker/randomness/number/NumberSettingsDialog.java, src/com/fwdekker/randomness/string/InsertRandomString.java, src/com/fwdekker/randomness/string/StringSettings.java, src/com/fwdekker/randomness/string/StringSettingsAction.java, src/com/fwdekker/randomness/string/StringSettingsDialog.java
Move settings to their own class.
=> Settings model

src/main/java/com/fwdekker/randomness/Settings.java, src/main/java/com/fwdekker/randomness/decimal/DecimalSettings.java, src/main/java/com/fwdekker/randomness/decimal/DecimalSettingsDialog.java, src/main/java/com/fwdekker/randomness/decimal/InsertRandomDecimal.java, src/main/java/com/fwdekker/randomness/integer/InsertRandomInteger.java, src/main/java/com/fwdekker/randomness/integer/IntegerSettings.java, src/main/java/com/fwdekker/randomness/integer/IntegerSettingsDialog.java, src/main/java/com/fwdekker/randomness/string/InsertRandomString.java, src/main/java/com/fwdekker/randomness/string/StringSettings.java, src/main/java/com/fwdekker/randomness/string/StringSettingsDialog.java, src/main/resources/META-INF/plugin.xml
=> Persistent settings

src/main/java/com/fwdekker/randomness/string/Alphabet.java, src/main/java/com/fwdekker/randomness/string/InsertRandomString.java, src/main/java/com/fwdekker/randomness/string/StringSettings.java, src/main/java/com/fwdekker/randomness/string/StringSettingsDialog.form, src/main/java/com/fwdekker/randomness/string/StringSettingsDialog.java
=> String alphabet

README.md, src/main/java/com/fwdekker/randomness/decimal/InsertRandomDecimal.java, src/main/java/com/fwdekker/randomness/integer/InsertRandomInteger.java, src/main/java/com/fwdekker/randomness/string/InsertRandomString.java
=> Secure random

src/main/java/com/fwdekker/randomness/string/StringSettingsDialog.form, src/main/java/com/fwdekker/randomness/string/StringSettingsDialog.java
=> Replace switches with streams

.travis.yml, build.gradle, gradle.properties, src/main/java/com/fwdekker/randomness/decimal/DecimalSettingsDialog.form, src/main/java/com/fwdekker/randomness/decimal/DecimalSettingsDialog.java, src/main/java/com/fwdekker/randomness/string/StringSettingsDialog.java, src/test/java/com/fwdekker/randomness/decimal/DecimalSettingsDialogTest.java
Sets up a framework for UI testing, and applies this framework to test the `DecimalSettingsDialog` class.
=> DecimalSettingsDialog tests

README.md, src/main/resources/META-INF/plugin.xml
=> Change default key binding

src/main/java/com/fwdekker/randomness/NamedItem.java, src/test/unit/java/com/fwdekker/randomness/NamedItemTest.java
This class can (and will) be used to give names to objects that do not inherently have a name.
=> Add and test NamedItem class

src/main/java/com/fwdekker/randomness/ValidationException.java, src/main/java/com/fwdekker/randomness/Validator.java, src/main/java/com/fwdekker/randomness/decimal/DecimalSettingsDialog.form, src/main/java/com/fwdekker/randomness/decimal/DecimalSettingsDialog.java, src/main/java/com/fwdekker/randomness/integer/InsertRandomInteger.java, src/main/java/com/fwdekker/randomness/integer/IntegerSettings.java, src/main/java/com/fwdekker/randomness/integer/IntegerSettingsDialog.form, src/main/java/com/fwdekker/randomness/integer/IntegerSettingsDialog.java, src/main/java/com/fwdekker/randomness/string/StringSettingsDialog.form, src/main/java/com/fwdekker/randomness/string/StringSettingsDialog.java, src/test/unit/java/com/fwdekker/randomness/decimal/DecimalSettingsDialogTest.java, src/test/unit/java/com/fwdekker/randomness/integer/IntegerSettingsDialogTest.java, src/test/unit/java/com/fwdekker/randomness/string/StringSettingsDialogTest.java
* Adds much more input validation.
* Fixes #38.
* Reduces validation complexity using the new `Validator` class.
* Tests much more input validation.
* Improves test performance by using fewer input simulations.
* Adds support for values ≥ 2^31 and < 2^31 to integer settings.
=> Long ranges

src/main/java/com/fwdekker/randomness/decimal/DecimalSettings.java, src/main/java/com/fwdekker/randomness/decimal/DecimalSettingsDialog.form, src/main/java/com/fwdekker/randomness/decimal/DecimalSettingsDialog.java, src/main/java/com/fwdekker/randomness/decimal/InsertRandomDecimal.java, src/main/java/com/fwdekker/randomness/ui/ButtonGroupHelper.java, src/test/unit/java/com/fwdekker/randomness/decimal/DecimalSettingsDialogTest.java, src/test/unit/java/com/fwdekker/randomness/decimal/InsertRandomDecimalSymbolTest.java
=> Decimal formatting options

src/main/java/com/fwdekker/randomness/InsertDataAction.java, src/main/java/com/fwdekker/randomness/InsertRandomSomething.java, src/main/java/com/fwdekker/randomness/array/ArraySettings.java, src/main/java/com/fwdekker/randomness/array/ArraySettingsAction.java, src/main/java/com/fwdekker/randomness/array/ArraySettingsDialog.form, src/main/java/com/fwdekker/randomness/array/ArraySettingsDialog.java, src/main/java/com/fwdekker/randomness/array/package-info.java, src/main/java/com/fwdekker/randomness/decimal/InsertRandomDecimal.java, src/main/java/com/fwdekker/randomness/integer/InsertRandomInteger.java, src/main/java/com/fwdekker/randomness/string/InsertRandomString.java, src/main/java/com/fwdekker/randomness/word/InsertRandomWord.java, src/main/resources/META-INF/plugin.xml, src/test/unit/java/com/fwdekker/randomness/InsertRandomSomethingTest.java, src/test/unit/java/com/fwdekker/randomness/array/ArraySettingsDialogTest.java, src/test/unit/java/com/fwdekker/randomness/array/ArraySettingsTest.java, src/test/unit/java/com/fwdekker/randomness/decimal/InsertRandomDecimalSymbolTest.java, src/test/unit/java/com/fwdekker/randomness/decimal/InsertRandomDecimalTest.java, src/test/unit/java/com/fwdekker/randomness/integer/InsertRandomIntegerSymbolTest.java, src/test/unit/java/com/fwdekker/randomness/integer/InsertRandomIntegerTest.java, src/test/unit/java/com/fwdekker/randomness/string/InsertRandomStringTest.java, src/test/unit/java/com/fwdekker/randomness/word/InsertRandomWordTest.java
Implements the ability to generate arrays/lists/vectors of random values, as suggested in #54.
=> Generate arrays

README.md
Describes Randomness' features in the README, and illustrates it with some images.
This PR also makes the `Release` badge link the the IntelliJ plugin repo rather than the GitHub release, because the GitHub release should be downloaded only in exceptional circumstances.
A live version of the updated README can be found [here](https://github.com/FWDekker/intellij-randomness/blob/98d67de3f15545ae55abcc8450fc6aea35406d94/README.md).
=> Add description of features to README.md

src/main/java/com/fwdekker/randomness/array/ArraySettingsDialog.form, src/test/java/com/fwdekker/randomness/array/ArraySettingsDialogTest.java
=> Implement newline character as array separator

src/main/java/com/fwdekker/randomness/word/WordSettingsDialog.java
=> Detect dictionary invalidity upon insertion

src/main/java/com/fwdekker/randomness/array/ArraySettingsDialog.java, src/test/java/com/fwdekker/randomness/DataInsertActionIntegrationTest.java, src/test/java/com/fwdekker/randomness/array/ArraySettingsDialogTest.java
Removes two suppressions that are no longer necessary, and removes an unused parameter in another suppression.
=> Remove unnecessary suppressions

src/main/java/com/fwdekker/randomness/string/Alphabet.java
=> Add option to generate hexadecimal strings

src/main/java/com/fwdekker/randomness/DataGroupAction.java, src/main/java/com/fwdekker/randomness/PopupAction.java, src/main/java/com/fwdekker/randomness/uuid/UuidArrayInsertAction.java, src/main/java/com/fwdekker/randomness/uuid/UuidGroupAction.java, src/main/java/com/fwdekker/randomness/uuid/UuidInsertAction.java, src/main/java/com/fwdekker/randomness/uuid/package-info.java, src/main/resources/META-INF/plugin.xml
=> Implement generation of type 4 UUIDs

src/main/java/com/fwdekker/randomness/string/StringInsertAction.java, src/test/java/com/fwdekker/randomness/string/StringInsertActionTest.java
I forgot to actually apply the capitalisation in #99, so here it is.
=> Fix string capitalisation

src/main/java/com/fwdekker/randomness/DataGroupAction.java, src/main/java/com/fwdekker/randomness/string/StringSettings.java, src/main/java/com/fwdekker/randomness/uuid/UuidGroupAction.java, src/main/java/com/fwdekker/randomness/uuid/UuidInsertAction.java, src/main/java/com/fwdekker/randomness/uuid/UuidSettings.java, src/main/java/com/fwdekker/randomness/uuid/UuidSettingsAction.java, src/main/java/com/fwdekker/randomness/uuid/UuidSettingsDialog.form, src/main/java/com/fwdekker/randomness/uuid/UuidSettingsDialog.java, src/main/resources/META-INF/plugin.xml, src/test/java/com/fwdekker/randomness/uuid/UuidInsertActionTest.java, src/test/java/com/fwdekker/randomness/uuid/UuidSettingsDialogTest.java, src/test/java/com/fwdekker/randomness/uuid/UuidSettingsTest.java
Adds the ability to add quotation marks around generated UUIDs (or to not do that), similar to the quotation settings for strings.
=> UUID settings

build.gradle, src/main/java/com/fwdekker/randomness/CapitalizationMode.java, src/main/java/com/fwdekker/randomness/DataGroupAction.java, src/main/java/com/fwdekker/randomness/decimal/DecimalGroupAction.java, src/main/java/com/fwdekker/randomness/integer/IntegerGroupAction.java, src/main/java/com/fwdekker/randomness/string/StringGroupAction.java, src/main/java/com/fwdekker/randomness/uuid/UuidGroupAction.java, src/main/java/com/fwdekker/randomness/uuid/UuidSettingsDialog.java, src/main/java/com/fwdekker/randomness/word/WordGroupAction.java
Currently, the `master` branch contains a number of (minor) static analysis errors. This indicates that I am not sufficiently aware of the static analysis tools. To increase awareness, this PR makes failing static analysis cause the build to fail. Additionally, it fixes any remaining static analysis errors.
=> Static analysis fixes

.config/detekt/.detekt.yml, .editorconfig, build.gradle, gradle.properties, src/main/kotlin/com/fwdekker/randomness/Cache.kt, src/main/kotlin/com/fwdekker/randomness/DataActions.kt, src/main/kotlin/com/fwdekker/randomness/decimal/DecimalSettings.kt, src/main/kotlin/com/fwdekker/randomness/ui/ButtonGroupHelper.kt, src/main/kotlin/com/fwdekker/randomness/ui/JBPopupHelper.kt, src/main/kotlin/com/fwdekker/randomness/ui/JEditableList.kt, src/main/kotlin/com/fwdekker/randomness/ui/JLongSpinner.kt, src/main/kotlin/com/fwdekker/randomness/word/Dictionary.kt, src/main/kotlin/com/fwdekker/randomness/word/WordActions.kt
=> Configure detekt

.codecov.yml, .travis.yml, README.md, build.gradle
=> Set up Codecov

src/main/java/com/fwdekker/randomness/word/WordSettingsDialog.java, src/main/kotlin/com/fwdekker/randomness/word/WordSettingsDialogHelper.kt, src/test/kotlin/com/fwdekker/randomness/word/WordSettingsDialogTest.kt
Fixes #134 and #136.
Additionally, code quality was improved by adding some helper functions.
=> Improve word length error messages and cache resets.

build.gradle, src/main/resources/META-INF/change-notes.html, src/main/resources/META-INF/description.html, src/main/resources/META-INF/plugin.xml
* Moves the plugin description to a `description.html` file.
* Adds changes notes in a `change-notes.html` file which is patched into `plugin.xml`.
* Changes IDE compatibility to 171+ instead of 145+ because Randomness wasn't actually compatible with those earlier versions.
* Reformats `plugin.xml`.
=> Add change notes, restructure xml and fix compatibility

src/main/java/com/fwdekker/randomness/decimal/DecimalSettingsDialog.form, src/main/java/com/fwdekker/randomness/decimal/DecimalSettingsDialog.java, src/main/kotlin/com/fwdekker/randomness/decimal/DecimalActions.kt, src/main/kotlin/com/fwdekker/randomness/decimal/DecimalSettings.kt, src/test/kotlin/com/fwdekker/randomness/decimal/DecimalInsertActionSeparatorTest.kt, src/test/kotlin/com/fwdekker/randomness/decimal/DecimalInsertActionTest.kt, src/test/kotlin/com/fwdekker/randomness/decimal/DecimalSettingsDialogTest.kt, src/test/kotlin/com/fwdekker/randomness/decimal/DecimalSettingsTest.kt
Fixes #141.
Also updates some of the decimal settings tests for clarity.
=> Leading zeroes

src/main/java/com/fwdekker/randomness/string/StringSettingsComponent.java, src/main/java/com/fwdekker/randomness/string/StringSettingsDialog.form, src/main/java/com/fwdekker/randomness/string/SymbolSetDialog.form, src/main/java/com/fwdekker/randomness/string/SymbolSetDialog.java, src/main/java/com/fwdekker/randomness/word/WordSettingsComponent.java, src/main/kotlin/com/fwdekker/randomness/string/StringActions.kt, src/main/kotlin/com/fwdekker/randomness/string/StringSettings.kt, src/main/kotlin/com/fwdekker/randomness/string/SymbolSet.kt, src/main/kotlin/com/fwdekker/randomness/ui/JEditableList.kt, src/test/kotlin/com/fwdekker/randomness/string/StringInsertActionTest.kt, src/test/kotlin/com/fwdekker/randomness/string/StringSettingsComponentTest.kt, src/test/kotlin/com/fwdekker/randomness/string/SymbolSetDialogTest.kt
Fixes #155.
(Additionally, slightly upgrades the look of `JEditableList` by making it extend from `JBList`.)
=> Custom symbol sets

src/main/java/com/fwdekker/randomness/string/SymbolSetDialog.form, src/main/kotlin/com/fwdekker/randomness/decimal/DecimalActions.kt, src/main/resources/META-INF/plugin.xml, src/test/kotlin/com/fwdekker/randomness/ui/JCheckBoxListTest.kt
* Assigns labels to input fields where appropriate.
* Uses Kotlin functions instead of Java functions where possible.
* Removes redundant `serviceInterface` properties from `plugin.xml`.
* Renames `JEditableListTest` to `JCheckBoxListTest`. Previously only the file was renamed.
=> Perform miscellaneous fixes

src/main/kotlin/com/fwdekker/randomness/ui/JCheckBoxTable.kt, src/test/kotlin/com/fwdekker/randomness/ui/JCheckBoxTableTest.kt
Fixes a bug where bundled dictionaries could not be activated.
(And removes some unused code now that I'm at it.)
=> Fix bug with activating dictionaries

build.gradle, gradle.properties, src/test/kotlin/com/fwdekker/randomness/CacheTest.kt, src/test/kotlin/com/fwdekker/randomness/CapitalizationModeTest.kt, src/test/kotlin/com/fwdekker/randomness/array/ArraySettingsComponentTest.kt, src/test/kotlin/com/fwdekker/randomness/array/ArraySettingsTest.kt, src/test/kotlin/com/fwdekker/randomness/decimal/DecimalSettingsComponentTest.kt, src/test/kotlin/com/fwdekker/randomness/decimal/DecimalSettingsTest.kt, src/test/kotlin/com/fwdekker/randomness/integer/IntegerSettingsComponentTest.kt, src/test/kotlin/com/fwdekker/randomness/integer/IntegerSettingsTest.kt, src/test/kotlin/com/fwdekker/randomness/string/StringSettingsComponentTest.kt, src/test/kotlin/com/fwdekker/randomness/string/StringSettingsTest.kt, src/test/kotlin/com/fwdekker/randomness/string/SymbolSetTest.kt, src/test/kotlin/com/fwdekker/randomness/ui/ButtonGroupKtTest.kt, src/test/kotlin/com/fwdekker/randomness/ui/JCheckBoxTableTest.kt, src/test/kotlin/com/fwdekker/randomness/ui/JNumberSpinnerTest.kt, src/test/kotlin/com/fwdekker/randomness/uuid/UuidSettingsComponentTest.kt, src/test/kotlin/com/fwdekker/randomness/uuid/UuidSettingsTest.kt, src/test/kotlin/com/fwdekker/randomness/word/DictionaryTest.kt, src/test/kotlin/com/fwdekker/randomness/word/WordInsertActionTest.kt, src/test/kotlin/com/fwdekker/randomness/word/WordSettingsComponentTest.kt, src/test/kotlin/com/fwdekker/randomness/word/WordSettingsTest.kt
Reverts #177. Ever since this PR was merged, builds have been failing unexpectedly on Travis (but not locally). Migration should be postponed.
=> Revert "Spek 2"

src/main/kotlin/com/fwdekker/randomness/string/SymbolSetTable.kt, src/main/kotlin/com/fwdekker/randomness/ui/ActivityTableModelEditor.kt, src/main/kotlin/com/fwdekker/randomness/word/Dictionary.kt, src/main/kotlin/com/fwdekker/randomness/word/DictionaryTable.kt, src/test/kotlin/com/fwdekker/randomness/string/StringSettingsComponentTest.kt, src/test/kotlin/com/fwdekker/randomness/ui/ActivityTableModelEditorTest.kt, src/test/kotlin/com/fwdekker/randomness/word/DictionaryTableTest.kt, src/test/kotlin/com/fwdekker/randomness/word/DictionaryTest.kt, src/test/kotlin/com/fwdekker/randomness/word/WordSettingsComponentTest.kt
A series of small bug fixes and enhancements before the release.
* Entries are now cloned deeply, meaning that a new datum is created instead of keeping the reference to the old one.
* New entries are now enabled by default.
=> Quality control

.codecov.yml, README.md, build.gradle, gradle.properties
And
* update Codecov configuration to reflect 80% coverage target,
* downgrade Dokka because the old package overview is easier to read,
* update some dependencies.
Fixes #201.
=> Extend list of features in README

src/main/kotlin/com/fwdekker/randomness/DataActions.kt, src/main/kotlin/com/fwdekker/randomness/decimal/DecimalActions.kt, src/main/kotlin/com/fwdekker/randomness/integer/IntegerActions.kt, src/main/kotlin/com/fwdekker/randomness/string/StringActions.kt, src/main/kotlin/com/fwdekker/randomness/string/StringSettingsComponent.form, src/main/kotlin/com/fwdekker/randomness/word/WordSettingsComponent.form, src/test/kotlin/com/fwdekker/randomness/DataInsertActionIntegrationTest.kt, src/test/kotlin/com/fwdekker/randomness/DataInsertActionTest.kt, src/test/kotlin/com/fwdekker/randomness/array/DataInsertArrayActionTest.kt, src/test/kotlin/com/fwdekker/randomness/decimal/DecimalInsertActionTest.kt, src/test/kotlin/com/fwdekker/randomness/integer/IntegerInsertActionTest.kt, src/test/kotlin/com/fwdekker/randomness/string/StringInsertActionTest.kt
Fixes #208 and
* fixes string preview seed,
* fixes word/string form radio button horizontal layout, and
* rewrites some JUnit test to a Spek test.
=> Increase error robustness

README.md, src/main/kotlin/com/fwdekker/randomness/DataActions.kt, src/main/kotlin/com/fwdekker/randomness/PopupAction.kt, src/main/resources/META-INF/change-notes.html
=> Allow inserting same string at multiple carets

src/main/kotlin/com/fwdekker/randomness/DataActions.kt, src/main/kotlin/com/fwdekker/randomness/array/ArraySettingsAction.kt, src/main/kotlin/com/fwdekker/randomness/decimal/DecimalActions.kt, src/main/kotlin/com/fwdekker/randomness/integer/IntegerActions.kt, src/main/kotlin/com/fwdekker/randomness/string/StringActions.kt, src/main/kotlin/com/fwdekker/randomness/uuid/UuidActions.kt, src/main/kotlin/com/fwdekker/randomness/word/WordActions.kt
=> Rename `SettingsAction` to `DataSettingsAction`

src/main/kotlin/com/fwdekker/randomness/PopupAction.kt, src/main/resources/META-INF/change-notes.html
=> Better popup

src/main/kotlin/com/fwdekker/randomness/string/SymbolSetTable.kt, src/main/kotlin/com/fwdekker/randomness/ui/ActivityTableModelEditor.kt, src/main/kotlin/com/fwdekker/randomness/word/DictionaryTable.kt, src/main/resources/META-INF/change-notes.html, src/main/resources/META-INF/plugin.xml, src/test/kotlin/com/fwdekker/randomness/ui/ActivityTableModelEditorTest.kt, src/test/kotlin/com/fwdekker/randomness/ui/PreviewPanelTest.kt
=> Add actionable instruction if table is empty

src/main/kotlin/com/fwdekker/randomness/DataActions.kt
=> Remove basic action from action groups

README.md, src/main/kotlin/com/fwdekker/randomness/DataActions.kt, src/main/kotlin/com/fwdekker/randomness/PopupAction.kt, src/main/kotlin/com/fwdekker/randomness/SettingsConfigurable.kt, src/main/kotlin/com/fwdekker/randomness/ui/JBPopupHelper.kt, src/main/resources/META-INF/change-notes.html
=> Multiple modifiers

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/question.md, README.md, src/main/kotlin/com/fwdekker/randomness/array/ArraySettingsComponent.kt, src/main/kotlin/com/fwdekker/randomness/decimal/DecimalSettingsComponent.kt, src/main/kotlin/com/fwdekker/randomness/integer/IntegerSettingsComponent.kt, src/main/kotlin/com/fwdekker/randomness/string/StringSettingsComponent.kt, src/main/kotlin/com/fwdekker/randomness/ui/JNumberSpinners.kt, src/main/kotlin/com/fwdekker/randomness/ui/JSpinnerRange.kt, src/main/kotlin/com/fwdekker/randomness/word/WordSettingsComponent.kt, src/main/resources/META-INF/change-notes.html, src/test/kotlin/com/fwdekker/randomness/array/ArraySettingsComponentTest.kt, src/test/kotlin/com/fwdekker/randomness/decimal/DecimalSettingsComponentTest.kt, src/test/kotlin/com/fwdekker/randomness/integer/IntegerSettingsComponentTest.kt, src/test/kotlin/com/fwdekker/randomness/string/StringSettingsComponentTest.kt, src/test/kotlin/com/fwdekker/randomness/ui/JNumberSpinnerTest.kt, src/test/kotlin/com/fwdekker/randomness/word/WordSettingsComponentTest.kt
Fixes #235.
(Also secretly contains some improvements over #234.)
=> Better spinner messages

src/main/kotlin/com/fwdekker/randomness/string/StringSettingsComponent.form, src/main/kotlin/com/fwdekker/randomness/string/StringSettingsComponent.kt, src/main/kotlin/com/fwdekker/randomness/ui/PreviewPanel.form, src/main/kotlin/com/fwdekker/randomness/ui/PreviewPanel.kt, src/main/kotlin/com/fwdekker/randomness/word/WordSettingsComponent.form, src/main/kotlin/com/fwdekker/randomness/word/WordSettingsComponent.kt
=> Replace titled panel borders with separators

src/main/kotlin/com/fwdekker/randomness/SettingsComponent.kt, src/main/kotlin/com/fwdekker/randomness/array/ArraySettings.kt, src/main/kotlin/com/fwdekker/randomness/array/ArraySettingsComponent.kt, src/main/kotlin/com/fwdekker/randomness/decimal/DecimalSettings.kt, src/main/kotlin/com/fwdekker/randomness/decimal/DecimalSettingsComponent.kt, src/main/kotlin/com/fwdekker/randomness/integer/IntegerSettings.kt, src/main/kotlin/com/fwdekker/randomness/integer/IntegerSettingsComponent.kt, src/main/kotlin/com/fwdekker/randomness/string/StringSettings.kt, src/main/kotlin/com/fwdekker/randomness/string/StringSettingsComponent.kt, src/main/kotlin/com/fwdekker/randomness/uuid/UuidSettings.kt, src/main/kotlin/com/fwdekker/randomness/uuid/UuidSettingsComponent.kt, src/main/kotlin/com/fwdekker/randomness/word/WordSettings.kt, src/main/kotlin/com/fwdekker/randomness/word/WordSettingsComponent.kt, src/main/resources/META-INF/change-notes.html, src/test/kotlin/com/fwdekker/randomness/DummySettingsComponent.kt
Fixes #242. This PR does not actually add more default schemes; it only adds the code to make it easier to do this in the future. That's because I can't currently think of any good default schemes to add.
=> Add infrastructure for multiple default schemes

src/main/kotlin/com/fwdekker/randomness/string/SymbolSetTable.kt, src/main/kotlin/com/fwdekker/randomness/ui/ActivityTableModelEditor.kt, src/main/resources/META-INF/change-notes.html
=> Focus on first editable column in tables

src/main/kotlin/com/fwdekker/randomness/Cache.kt, src/main/kotlin/com/fwdekker/randomness/DummyActions.kt, src/main/kotlin/com/fwdekker/randomness/SettingsComponent.kt, src/main/kotlin/com/fwdekker/randomness/array/ArraySettings.kt, src/main/kotlin/com/fwdekker/randomness/decimal/DecimalActions.kt, src/main/kotlin/com/fwdekker/randomness/decimal/DecimalSettings.kt, src/main/kotlin/com/fwdekker/randomness/integer/IntegerActions.kt, src/main/kotlin/com/fwdekker/randomness/integer/IntegerSettings.kt, src/main/kotlin/com/fwdekker/randomness/string/StringActions.kt, src/main/kotlin/com/fwdekker/randomness/string/StringSettings.kt, src/main/kotlin/com/fwdekker/randomness/ui/PreviewPanel.kt, src/main/kotlin/com/fwdekker/randomness/uuid/UuidActions.kt, src/main/kotlin/com/fwdekker/randomness/uuid/UuidSettings.kt, src/main/kotlin/com/fwdekker/randomness/word/WordActions.kt, src/main/kotlin/com/fwdekker/randomness/word/WordSettings.kt
=> Update `@see` and `@property` tags

src/main/kotlin/com/fwdekker/randomness/ui/ActivityTableModelEditor.kt
=> Focus editable col after adding row

src/main/kotlin/com/fwdekker/randomness/string/SymbolSetTable.kt, src/main/resources/META-INF/change-notes.html
=> Use simple parser for expandable editor

src/main/kotlin/com/fwdekker/randomness/string/SymbolSet.kt, src/main/resources/META-INF/change-notes.html, src/test/kotlin/com/fwdekker/randomness/string/SymbolSetTest.kt
=> Remove duplicate symbols from symbol sets

src/main/kotlin/com/fwdekker/randomness/PopupAction.kt, src/main/resources/META-INF/change-notes.html
=> Display settings only if no editor is selected

src/main/kotlin/com/fwdekker/randomness/PopupAction.kt, src/main/kotlin/com/fwdekker/randomness/integer/IntegerSettingsComponent.kt, src/main/kotlin/com/fwdekker/randomness/string/StringSettingsComponent.kt, src/main/kotlin/com/fwdekker/randomness/string/SymbolSetTable.kt, src/main/kotlin/com/fwdekker/randomness/ui/ActivityTableModelEditor.kt, src/main/kotlin/com/fwdekker/randomness/ui/JNumberSpinners.kt, src/main/kotlin/com/fwdekker/randomness/ui/JSpinnerRange.kt, src/main/kotlin/com/fwdekker/randomness/word/DictionaryTable.kt, src/main/kotlin/com/fwdekker/randomness/word/WordSettingsComponent.kt, src/main/resources/META-INF/change-notes.html, src/test/kotlin/com/fwdekker/randomness/string/StringSettingsComponentTest.kt
Fixes #284.
(Also fixes the title of the settings-only popup introduced in #268.)
=> Error messages

src/main/kotlin/com/fwdekker/randomness/SettingsComponent.kt, src/main/kotlin/com/fwdekker/randomness/SettingsConfigurable.kt, src/main/kotlin/com/fwdekker/randomness/ValidationInfo.kt, src/main/kotlin/com/fwdekker/randomness/string/SymbolSetTable.kt, src/main/kotlin/com/fwdekker/randomness/ui/JNumberSpinners.kt, src/main/kotlin/com/fwdekker/randomness/ui/JSpinnerRange.kt, src/main/kotlin/com/fwdekker/randomness/uuid/UuidSettingsComponent.kt, src/main/kotlin/com/fwdekker/randomness/word/DictionaryTable.kt, src/main/kotlin/com/fwdekker/randomness/word/WordSettingsComponent.kt
Fixes #286. Sadly, quick fixes haven't actually been implemented for configurables, so the user won't notice a difference. One day in the future, however, this _may_ come in handy.
=> Add quick fix for word lengths

README.md, src/main/kotlin/com/fwdekker/randomness/ValidationInfo.kt, src/main/kotlin/com/fwdekker/randomness/string/StringSettings.kt, src/main/resources/META-INF/change-notes.html, src/main/resources/META-INF/description.html, src/test/kotlin/com/fwdekker/randomness/string/StringSettingsTest.kt
=> Ensure emoji persist between reloads

src/main/kotlin/com/fwdekker/randomness/array/ArraySettingsComponent.form, src/main/kotlin/com/fwdekker/randomness/decimal/DecimalSettingsComponent.form, src/main/kotlin/com/fwdekker/randomness/integer/IntegerSettingsComponent.form, src/main/kotlin/com/fwdekker/randomness/string/StringSettingsComponent.form, src/main/kotlin/com/fwdekker/randomness/uuid/UuidSettingsComponent.form, src/main/kotlin/com/fwdekker/randomness/word/WordSettingsComponent.form, src/main/resources/META-INF/change-notes.html
=> Make radio button sizes independent

src/main/kotlin/com/fwdekker/randomness/PopupAction.kt, src/main/resources/META-INF/change-notes.html
=> Fix support for modifier keys in settings popup

.github/CONTRIBUTING.md, .github/RELEASE_CHECKLIST.md
=> Create release checklist

src/main/kotlin/com/fwdekker/randomness/decimal/DecimalSettingsComponent.form, src/main/kotlin/com/fwdekker/randomness/integer/IntegerActions.kt, src/main/kotlin/com/fwdekker/randomness/integer/IntegerSettings.kt, src/main/kotlin/com/fwdekker/randomness/integer/IntegerSettingsComponent.form
=> Add presets and fix base behavior

src/main/kotlin/com/fwdekker/randomness/SettingsComponent.kt
=> Fix order of operations in scheme deletion

src/main/kotlin/com/fwdekker/randomness/array/ArraySettingsComponent.form, src/main/kotlin/com/fwdekker/randomness/decimal/DecimalSettingsComponent.form, src/main/kotlin/com/fwdekker/randomness/integer/IntegerSettingsComponent.form, src/main/kotlin/com/fwdekker/randomness/string/StringSettingsComponent.form, src/main/kotlin/com/fwdekker/randomness/word/WordSettingsComponent.form, src/main/resources/META-INF/change-notes.html
=> Fix mnemonics for spinners

src/main/kotlin/com/fwdekker/randomness/ErrorReporter.kt, src/main/resources/META-INF/plugin.xml
Also drops support for IDE versions below 2019.
Works towards #209.
=> Add privacy policy to error reporter

src/main/kotlin/com/fwdekker/randomness/ErrorReporter.kt
Fixes #333. See also #209, where the removal of the suppression is scheduled.
=> Remove usage of internal method

gradle.properties, src/main/resources/META-INF/change-notes.html
=> Bump version number, add change notes

src/main/kotlin/com/fwdekker/randomness/integer/IntegerActions.kt, src/main/kotlin/com/fwdekker/randomness/integer/IntegerSettings.kt, src/main/kotlin/com/fwdekker/randomness/integer/IntegerSettingsComponent.form, src/main/kotlin/com/fwdekker/randomness/integer/IntegerSettingsComponent.kt, src/main/kotlin/com/fwdekker/randomness/string/StringSettingsComponent.kt, src/main/resources/META-INF/change-notes.html, src/test/kotlin/com/fwdekker/randomness/integer/IntegerInsertActionTest.kt, src/test/kotlin/com/fwdekker/randomness/integer/IntegerSettingsComponentTest.kt, src/test/kotlin/com/fwdekker/randomness/integer/IntegerSettingsTest.kt
Fixes #346. Quite straightforward.
=> Add capitalisation option for integers

src/main/kotlin/com/fwdekker/randomness/integer/IntegerSettings.kt, src/main/resources/META-INF/change-notes.html
=> Add preset for byte-type integer

src/main/kotlin/com/fwdekker/randomness/array/ArraySettingsComponent.form, src/main/kotlin/com/fwdekker/randomness/decimal/DecimalSettingsComponent.form, src/main/kotlin/com/fwdekker/randomness/integer/IntegerSettingsComponent.form, src/main/kotlin/com/fwdekker/randomness/integer/IntegerSettingsComponent.kt, src/main/kotlin/com/fwdekker/randomness/string/StringSettingsComponent.form, src/main/kotlin/com/fwdekker/randomness/word/WordSettingsComponent.form, src/test/kotlin/com/fwdekker/randomness/integer/IntegerSettingsComponentTest.kt
Fixes #374. Also fixes #371 for real by actually removing the limit from validation.
=> Use more reasonably sized input fields

README.md, src/main/resources/META-INF/change-notes.html
Fixes #378.
Also adds some missing things to the current change notes.
=> Credit all contributors in the README

.github/ISSUE_TEMPLATE/bug_report.md, gradle.properties, src/main/resources/META-INF/change-notes.html
=> Bump version number, fix change notes

.config/detekt/.detekt.yml, gradle.properties, src/main/kotlin/com/fwdekker/randomness/DataActions.kt, src/main/kotlin/com/fwdekker/randomness/PopupAction.kt, src/main/kotlin/com/fwdekker/randomness/uds/UDSActions.kt, src/main/kotlin/com/fwdekker/randomness/uds/UDSParser.kt, src/main/kotlin/com/fwdekker/randomness/uds/UDSSettings.kt, src/main/kotlin/com/fwdekker/randomness/uds/UDSSettingsComponent.form, src/main/kotlin/com/fwdekker/randomness/uds/UDSSettingsComponent.kt, src/main/resources/META-INF/plugin.xml
Provides an (untested) first attempt at the UDS described in #365. This is by no means a final version, but I think the changes form a good, coherent base to continue working with. Currently, UDS is a separate data type for testing purposes.
My next step will be to experiment with creating the editor from #366.
This PR also updates a whole bunch of dependencies.
=> Basic unified data syntax implementation

src/main/kotlin/com/fwdekker/randomness/string/StringScheme.kt, src/main/kotlin/com/fwdekker/randomness/template/TemplateList.kt, src/main/kotlin/com/fwdekker/randomness/template/TemplateListEditor.kt, src/main/kotlin/com/fwdekker/randomness/template/TemplateReferenceEditor.kt, src/test/kotlin/com/fwdekker/randomness/string/StringSchemeTest.kt, src/test/kotlin/com/fwdekker/randomness/template/TemplateListEditorTest.kt, src/test/kotlin/com/fwdekker/randomness/template/TemplateListTest.kt, src/test/kotlin/com/fwdekker/randomness/template/TemplateReferenceEditorTest.kt
Allows users to reset individual schemes/templates.
=> Allow resetting per scheme/template

README.md, build.gradle.kts, gradle.properties, src/main/kotlin/com/fwdekker/randomness/PopupAction.kt, src/main/kotlin/com/fwdekker/randomness/template/TemplateActions.kt, src/main/kotlin/com/fwdekker/randomness/word/WordSchemeEditor.kt, src/main/resources/META-INF/change-notes.html, src/main/resources/META-INF/description.html
Prepare for v3.0.0-beta.1!
Includes all required changes to launch the v3 beta! I plan to create an issue tomorrow announcing the beta, and requesting support from others to test it out :-)
=> Prepare release notes etc. for first v3 beta

LICENSE, gradle.properties, src/main/kotlin/com/fwdekker/randomness/PopupAction.kt, src/main/resources/META-INF/change-notes.html
It was done exactly the wrong way around before...
Also, prepare for the second beta!
=> Ensure popup correctly switches to settings-only

README.md
=> Update Shields badges

README.md, build.gradle.kts
This PR checks if all tooling still works properly.
=> Rename master branch to main

src/main/kotlin/com/fwdekker/randomness/Settings.kt, src/main/kotlin/com/fwdekker/randomness/template/Template.kt, src/test/kotlin/com/fwdekker/randomness/template/TemplateTest.kt
* Allows the Randomness config to be exported.
* Removes the old Randomness config when it is still present.
* Fixes #466.
=> Files and seeds

build.gradle.kts, gradle.properties, gradle/wrapper/gradle-wrapper.properties, src/main/kotlin/com/fwdekker/randomness/PopupAction.kt, src/main/kotlin/com/fwdekker/randomness/State.kt, src/main/kotlin/com/fwdekker/randomness/array/ArrayDecoratorEditor.kt, src/main/kotlin/com/fwdekker/randomness/string/StringSchemeEditor.kt, src/main/kotlin/com/fwdekker/randomness/template/TemplateActionLoader.kt, src/main/kotlin/com/fwdekker/randomness/template/TemplateActions.kt, src/main/kotlin/com/fwdekker/randomness/template/TemplateJTree.kt, src/main/kotlin/com/fwdekker/randomness/template/TemplateReferenceEditor.kt, src/main/kotlin/com/fwdekker/randomness/ui/InterfaceBuilderHelpers.kt, src/test/kotlin/com/fwdekker/randomness/array/ArrayDecoratorEditorTest.kt, src/test/kotlin/com/fwdekker/randomness/template/TemplateListEditorTest.kt, src/test/kotlin/com/fwdekker/randomness/template/TemplateReferenceTest.kt
Updates a whole bunch of dependencies (including the UUID generator, which was buggy in v4.0.0 and v4.0.1, but this was resolved at the start of 2023!), a few docs here and there, and fixes #463.
=> Deps and popup

src/main/kotlin/com/fwdekker/randomness/InsertAction.kt, src/main/kotlin/com/fwdekker/randomness/PopupAction.kt, src/test/kotlin/com/fwdekker/randomness/InsertActionTest.kt
=> Improve detection of read-only files

src/main/kotlin/com/fwdekker/randomness/template/TemplateList.kt
Fixes #486.
I know I can do better than this by adding more creative presets, but I'd rather not add a whole bunch of new dictionaries until #469 is resolved, as otherwise performance might significantly drop.
=> Slightly reorganise presets

.github/ISSUE_TEMPLATE/bug_report.md, .github/RELEASE_CHECKLIST.md, CHANGELOG.md, README.md, gradle.properties
=> Prepare release

CHANGELOG.md, src/main/kotlin/com/fwdekker/randomness/Icons.kt, src/test/kotlin/com/fwdekker/randomness/IconsTest.kt
Adds debug info for helping with debugging FWDekkerBot/intellij-randomness-issues#1.
=> Add debug info for non-square icons

CHANGELOG.md, src/main/kotlin/com/fwdekker/randomness/Icons.kt
Continuation of #538, relating to FWDekkerBot/intellij-randomness-issues#1.
=> Add even more debug info for issue R1

CHANGELOG.md
Describes the changes in the changelog.
=> Prepare for v3.3.5

src/main/kotlin/com/fwdekker/randomness/template/TemplateActions.kt
The error caused a stack overflow when inserting anything!
=> Fix error made when bumping API versions

CHANGELOG.md, src/main/kotlin/com/fwdekker/randomness/template/TemplateActions.kt
=> Focus on first scheme by default

src/main/kotlin/com/fwdekker/randomness/word/WordSchemeEditor.kt, src/main/resources/randomness.properties
=> Resolve HTML displayed in word list name

.github/workflows/cd.yml, .github/workflows/ci.yml, README.md, build.gradle.kts, gradle.properties
=> Deploy updates semi-automatically

.github/RELEASE_CHECKLIST.md, CHANGELOG.md, gradle.properties, src/main/kotlin/com/fwdekker/randomness/InsertAction.kt, src/main/kotlin/com/fwdekker/randomness/template/TemplateActions.kt, src/test/kotlin/com/fwdekker/randomness/InsertActionTest.kt, src/test/kotlin/com/fwdekker/randomness/template/TemplateActionTests.kt, src/test/kotlin/com/fwdekker/randomness/testhelpers/Tags.kt
Hopefully, this one _really_ fixes fwdekkerbot/intellij-randomness-issues#44. And by hopefully, I mean that I was able to reproduce the issue manually (see fwdekkerbot/intellij-randomness-issues#44 for more details), and with this fix, that reproduction procedure no longer gives the exception!
=> Set actions icons passively

.github/RELEASE_CHECKLIST.md, .github/workflows/cd.yml, CHANGELOG.md, README.md, src/main/kotlin/com/fwdekker/randomness/Bundle.kt, src/main/kotlin/com/fwdekker/randomness/Settings.kt, src/main/kotlin/com/fwdekker/randomness/State.kt, src/main/kotlin/com/fwdekker/randomness/Timestamp.kt, src/main/kotlin/com/fwdekker/randomness/template/TemplateJTree.kt, src/test/kotlin/com/fwdekker/randomness/SettingsFileManagerTest.kt, src/test/kotlin/com/fwdekker/randomness/SettingsTest.kt, src/test/resources/settings-upgrades/v3.4.1-v3.4.2-after.xml, src/test/resources/settings-upgrades/v3.4.1-v3.4.2-before.xml
* Updates the changelog to describe all recent changes.
* Update the changelog to include some "thank you"s for recent changes that, in hindsight, should have been there since the beginning.
* Fixes minor style issues detected by the IDE.
* Automatically check for some more issues in the `cd.yml` workflow.
There is no need to update the GitHub pages, this is done automatically during the `cd.yml` workflow.
Check that the build action does not fail!
=> Prepare for release v3.4.2
