src/main/java/com/fwdekker/randomness/SettingsAction.java
src/main/java/com/fwdekker/randomness/decimal/DecimalSettingsAction.java
src/main/java/com/fwdekker/randomness/decimal/DecimalSettingsDialog.form
src/main/java/com/fwdekker/randomness/decimal/DecimalSettingsDialog.java
src/main/java/com/fwdekker/randomness/integer/IntegerSettingsAction.java
src/main/java/com/fwdekker/randomness/integer/IntegerSettingsDialog.form
src/main/java/com/fwdekker/randomness/integer/IntegerSettingsDialog.java
src/main/java/com/fwdekker/randomness/string/StringSettingsAction.java
src/main/java/com/fwdekker/randomness/string/StringSettingsDialog.form
src/main/java/com/fwdekker/randomness/string/StringSettingsDialog.java

Makes settings dialogs extend from `DialogWrapper` rather than from `JDialog`. This makes the styling of the dialogs more consistent with the rest of the UI, gives better input validation (with feedback), and makes the sizes of dialogs persistent throughout a session.

IntelliJ dialogs

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

The extra lines in `build.gradle` are there for backwards-compatibility with Gradle plugins that have not been updated yet.

Upgrade Gradle to version 4.0.1

---

src/main/java/com/fwdekker/randomness/word/CapitalizationMode.java
src/main/java/com/fwdekker/randomness/word/WordSettings.java
src/main/java/com/fwdekker/randomness/word/WordSettingsDialog.form
src/main/java/com/fwdekker/randomness/word/WordSettingsDialog.java
src/test/java/com/fwdekker/randomness/word/CapitalizationModeTest.java
src/test/java/com/fwdekker/randomness/word/WordSettingsDialogTest.java

Fixes #61 and #62 by adding two new capitalisation rules:
* `First letter`: Capitalise The First Letter Of Each Word
* `Retain`: dO NoT ChAnGe The CapiTALIsatioN
Furthermore:
* The capitalisation mode `Normal` was renamed to `Sentence` to better explain its meaning.
* The default mode was changed from `Sentence` to `Retain`.

Word capitalisation rules

---

src/main/java/com/fwdekker/randomness/word/Dictionary.java
src/main/java/com/fwdekker/randomness/word/WordSettingsDialog.java
src/test/java/com/fwdekker/randomness/word/BundledDictionaryTest.java
src/test/java/com/fwdekker/randomness/word/DictionaryTest.java
src/test/java/com/fwdekker/randomness/word/UserDictionaryTest.java
src/test/java/com/fwdekker/randomness/word/WordSettingsDialogTest.java

Fixes #69 and implements part of the proposal in #65.
In particular, this PR
* Restructures the `Dictionary` class so that imlementations no longer need to work with files. As long as they can provide an `InputStream` to the dictionary content it's OK.
* Adds a `validate` method to `Dictionary` and co. that returns a `ValidationInfo`, similar to how other UI components do that. Admittedly, `ValidationInfo` may not have been the most suitable class semantically, but it does exactly what I want.
* Integrates this check into the word dialog.
Essentially, this PR makes sure that invalid dictionaries cannot be saved in the dialog, and progresses towards the other points proposed in #65.

Dictionary fixes

---

src/main/java/com/fwdekker/randomness/ui/JBPopupHelper.java
src/main/java/com/fwdekker/randomness/word/Dictionary.java
src/main/java/com/fwdekker/randomness/word/WordInsertAction.java
src/main/java/com/fwdekker/randomness/word/WordSettings.java
src/main/java/com/fwdekker/randomness/word/WordSettingsDialog.form
src/main/java/com/fwdekker/randomness/word/WordSettingsDialog.java
src/test/java/com/fwdekker/randomness/word/BundledDictionaryTest.java
src/test/java/com/fwdekker/randomness/word/DictionaryHelper.java
src/test/java/com/fwdekker/randomness/word/UserDictionaryTest.java
src/test/java/com/fwdekker/randomness/word/WordSettingsTest.java

Fixes #65.
* Implementations of `Dictionary` now have a static `validate(String)` method that returns whether the dictionary at the given path would be valid, and have an instance method `validate()` that returns whether the current instance is still valid.
* The above-mentioned `validate` methods are used in the `loadSettings` method of the `WordSettingsDialog` to filter out the invalid dictionaries so that these are not loaded.
* The `validate` methods are also used in `WordInsertAction` to display a popup indicating that at least one of the dictionaries has become invalid. No word will be inserted, and the user is directed towards the settings menu.
The responsibility of the filtering and validating lies with the `WordSettings` class because it is the only class that actually puts a …

Dictionary dialog fixes

---

src/test/java/com/fwdekker/randomness/decimal/DecimalSettingsDialogTest.java
src/test/java/com/fwdekker/randomness/string/StringSettingsDialogTest.java

When the flaky tests were removed in #77, the utility methods used by those tests (and only by those tests) were left in place. This triggered two PMD errors, which were not caught because the build is not set to fail on static analysis errors. This PR removes the aforementioned unused methods.

Remove unused methods in test classes

---

src/test/java/com/fwdekker/randomness/word/DictionaryFileHelper.java
src/test/java/com/fwdekker/randomness/word/UserDictionaryTest.java
src/test/java/com/fwdekker/randomness/word/WordSettingsTest.java

In the discussion on cafejojo/schaapi#45, it turned out that operating systems are not expected to clean up temporary files after use. Therefore, this PR adjusts the tests such that temporary files are deleted after running tests.
The `DictionaryHelper` class was renamed to `DictionaryFileHelper`, and has become stateful. Whenever a file is created through this helper, it is stored in a list. The `cleanUpDictionaries` method can then be called at any time to delete the files that have been created so far by that instance.

Delete temporary files after test completion

---

src/main/java/com/fwdekker/randomness/word/Dictionary.java
src/main/java/com/fwdekker/randomness/word/WordSettingsDialog.java
src/test/java/com/fwdekker/randomness/word/BundledDictionaryTest.java
src/test/java/com/fwdekker/randomness/word/DictionaryFileHelper.java
src/test/java/com/fwdekker/randomness/word/UserDictionaryTest.java

The contents of dictionaries are now refreshed each time the user saves the word settings.
Additionally, the cache is no longer used when a new dictionary is added. This will prevent the theoretical issue of a user trying to add an invalid dictionary, editing the source file, and then being unable to add the now-valid dictionary because the invalid version is still cached.

Dictionary dynamic reload

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

The IntelliJ plugin used some old classes that were deprecated, so it had to be updated as well.

Update Gradle to 4.10

---

gradle.properties

AssertJ was not updated from 3.8.0 to 3.11.0 because the Swing core is still at 3.8.0, and I'm not sure what effects it has on the compatibility.

Bump dependencies

---

src/main/java/com/fwdekker/randomness/Settings.java
src/main/java/com/fwdekker/randomness/array/ArraySettings.java
src/main/java/com/fwdekker/randomness/decimal/DecimalSettings.java
src/main/java/com/fwdekker/randomness/integer/IntegerSettings.java
src/main/java/com/fwdekker/randomness/string/StringSettings.java
src/main/java/com/fwdekker/randomness/uuid/UuidSettings.java
src/main/java/com/fwdekker/randomness/word/WordSettings.java
src/test/java/com/fwdekker/randomness/array/ArraySettingsTest.java
src/test/java/com/fwdekker/randomness/decimal/DecimalSettingsTest.java
src/test/java/com/fwdekker/randomness/integer/IntegerSettingsTest.java
src/test/java/com/fwdekker/randomness/string/StringSettingsTest.java
src/test/java/com/fwdekker/randomness/uuid/UuidSettingsTest.java
src/test/java/com/fwdekker/randomness/word/WordSettingsTest.java

Every `*Settings` class extended `Settings` and implemented `PersistentStateComponent`. In turn, `Settings` implemented `ApplicationComponent`. As a result, all `*Settings` classes were two types of components at once, even though the `ApplicationComponent` functionalities were not being used (and they were not even registered as application components in the `plugin.xml`).
This PR removes code related to `ApplicationComponent` because this plugin does not use application components.

Remove ApplicationComponent interface

---

src/main/java/com/fwdekker/randomness/array/ArraySettingsDialog.java
src/main/java/com/fwdekker/randomness/decimal/DecimalSettingsDialog.java
src/main/java/com/fwdekker/randomness/integer/IntegerSettingsDialog.java
src/main/java/com/fwdekker/randomness/string/StringSettingsDialog.java
src/main/java/com/fwdekker/randomness/word/WordSettingsDialog.java

Makes all `SettingsDialog` classes public; before, only `UuidSettingsDialog` was public.

Make access modifiers consistent

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

Updates Gradle to the latest version.
This update also updates the version of PMD that is used. Sadly, this introduced a large number of false positives. Rather than suppressing the individual false positives, I have decided to let builds pass regardless of PMD's status.

Update Gradle to v5.2.1

---

.codecov.yml

Stops Codecov from including the list of affected files in PR comments. These lists are ugly and not very useful anyway.

Exclude file lists from Codecov comments

---

src/main/java/com/fwdekker/randomness/decimal/DecimalSettingsDialog.java
src/main/java/com/fwdekker/randomness/integer/IntegerSettingsDialog.java
src/main/kotlin/com/fwdekker/randomness/array/ArraySettings.kt
src/main/kotlin/com/fwdekker/randomness/decimal/DecimalActions.kt
src/main/kotlin/com/fwdekker/randomness/decimal/DecimalSettings.kt
src/main/kotlin/com/fwdekker/randomness/integer/IntegerActions.kt
src/main/kotlin/com/fwdekker/randomness/integer/IntegerSettings.kt
src/main/kotlin/com/fwdekker/randomness/ui/JLongSpinner.kt
src/test/kotlin/com/fwdekker/randomness/decimal/DecimalInsertActionSymbolTest.kt
src/test/kotlin/com/fwdekker/randomness/decimal/DecimalSettingsDialogTest.kt
src/test/kotlin/com/fwdekker/randomness/decimal/DecimalSettingsTest.kt
src/test/kotlin/com/fwdekker/randomness/integer/IntegerInsertActionBaseTest.kt
src/test/kotlin/com/fwdekker/randomness/integer/IntegerInsertActionSymbolTest.kt
src/test/kotlin/com/fwdekker/randomness/integer/IntegerSettingsTest.kt
src/test/kotlin/com/fwdekker/randomness/ui/JLongSpinnerTest.kt

IntelliJ would fail to read a setting into a `Char` field. Therefore, all `Char` fields have been converted to `String` fields. Where the length of a field must be exactly one, a check is added to the setter.

Improve backwards compatibility for settings

---

src/main/kotlin/com/fwdekker/randomness/DataActions.kt
src/main/kotlin/com/fwdekker/randomness/ui/JBPopupHelper.kt
src/main/kotlin/com/fwdekker/randomness/word/WordActions.kt
src/test/kotlin/com/fwdekker/randomness/word/WordInsertActionTest.kt

Improves the error dialog that is shown when no data could be generated. Rather than using a JetBrains popup, it now uses a modal dialog. Additionally, the dialog now shows more descriptive errors for when no words could be generated.
| Before | After |
|---|---|
| ![before](https://user-images.githubusercontent.com/13442533/57095961-630bc500-6d14-11e9-8d79-3dd72ba28d8e.png) | ![after](https://user-images.githubusercontent.com/13442533/57095964-669f4c00-6d14-11e9-8962-578db61bed8a.PNG) |

Improve data generation error dialog

---

.config/detekt/.detekt.yml
src/main/kotlin/com/fwdekker/randomness/DataActions.kt
src/main/kotlin/com/fwdekker/randomness/ui/JBPopupHelper.kt
src/main/kotlin/com/fwdekker/randomness/ui/JNumberSpinners.kt

Fixes some Detekt violations that remained in the code. Detekt did not fail the build because the `console-reports` option apparently disables the check entirely instead of just disabling console output. Strange.

Address Detekt violations

---

src/main/kotlin/com/fwdekker/randomness/DataActions.kt
src/main/kotlin/com/fwdekker/randomness/string/StringSettings.kt
src/main/kotlin/com/fwdekker/randomness/ui/JNumberSpinners.kt
src/main/kotlin/com/fwdekker/randomness/ui/JSpinnerRange.kt
src/test/kotlin/com/fwdekker/randomness/decimal/DecimalSettingsDialogTest.kt
src/test/kotlin/com/fwdekker/randomness/integer/IntegerSettingsDialogTest.kt
src/test/kotlin/com/fwdekker/randomness/string/StringSettingsDialogTest.kt
src/test/kotlin/com/fwdekker/randomness/ui/JSpinnerRangeTest.kt
src/test/kotlin/com/fwdekker/randomness/word/WordSettingsDialogTest.kt

* Uses `HintManager` instead of `Messages` to show error messages when random data could not be generated.
* Changes some awkward wording in an error message.
* Fixes an error where decimals would incorrectly be truncated.
* Changes the default string capitalisation mode from upper to random.

Miscellaneous fixes

---

.config/detekt/.detekt.yml
src/main/java/com/fwdekker/randomness/decimal/DecimalSettingsDialog.java
src/main/java/com/fwdekker/randomness/integer/IntegerSettingsDialog.java
src/main/kotlin/com/fwdekker/randomness/array/ArraySettings.kt
src/main/kotlin/com/fwdekker/randomness/decimal/DecimalSettings.kt
src/main/kotlin/com/fwdekker/randomness/integer/IntegerSettings.kt
src/main/kotlin/com/fwdekker/randomness/string/StringSettings.kt
src/main/kotlin/com/fwdekker/randomness/uuid/UuidSettings.kt
src/main/kotlin/com/fwdekker/randomness/word/WordSettings.kt
src/test/kotlin/com/fwdekker/randomness/decimal/DecimalSettingsTest.kt
src/test/kotlin/com/fwdekker/randomness/integer/IntegerSettingsDialogTest.kt
src/test/kotlin/com/fwdekker/randomness/integer/IntegerSettingsTest.kt

Moves settings class properties to the constructor and makes the classes into data classes. This allows for easier comparison between settings instances. Because the settings serialiser currently cannot handle chars, `safeSet` methods have been added to check for the theoretical edge cases where a non-character-like string is set.

Turn settings classes into data classes

---

src/main/java/com/fwdekker/randomness/word/WordSettingsDialog.java

Because of a minor typo, saving word settings would result in the _available_ bundled dictionaries being overwritten by the _selected_ bundled dictionaries. This bug was able to slip by the tests because the tests supposed to cover this could not be written because of incompatibility between IntelliJ's file chooser and the UI test framework.

Fix issue with missing bundled dictionaries

---

src/main/kotlin/com/fwdekker/randomness/SettingsConfigurable.kt
src/test/kotlin/com/fwdekker/randomness/array/ArraySettingsComponentTest.kt
src/test/kotlin/com/fwdekker/randomness/decimal/DecimalSettingsComponentTest.kt
src/test/kotlin/com/fwdekker/randomness/integer/IntegerSettingsComponentTest.kt
src/test/kotlin/com/fwdekker/randomness/string/StringSettingsComponentTest.kt
src/test/kotlin/com/fwdekker/randomness/uuid/UuidSettingsComponentTest.kt
src/test/kotlin/com/fwdekker/randomness/word/WordSettingsComponentTest.kt

#149 had the unintended side effect of removing input validation from the interface. This PR puts it back in.
(Oh, and it also renames `WordSettingsDialogTest` to `WordSettingsComponentTest` because apparently that didn't happen in #151.)

Add input validation back in

---

src/main/java/com/fwdekker/randomness/decimal/DecimalSettingsComponent.java
src/main/java/com/fwdekker/randomness/integer/IntegerSettingsComponent.java
src/main/java/com/fwdekker/randomness/string/StringSettingsComponent.java
src/main/java/com/fwdekker/randomness/string/StringSettingsDialog.form
src/main/java/com/fwdekker/randomness/word/WordSettingsComponent.java
src/main/kotlin/com/fwdekker/randomness/DataActions.kt
src/main/kotlin/com/fwdekker/randomness/ui/JNumberSpinners.kt
src/main/kotlin/com/fwdekker/randomness/ui/JSpinnerRange.kt
src/test/kotlin/com/fwdekker/randomness/array/ArraySettingsComponentTest.kt
src/test/kotlin/com/fwdekker/randomness/decimal/DecimalSettingsComponentTest.kt
src/test/kotlin/com/fwdekker/randomness/integer/IntegerSettingsComponentTest.kt
src/test/kotlin/com/fwdekker/randomness/string/StringSettingsComponentTest.kt
src/test/kotlin/com/fwdekker/randomness/ui/JNumberSpinnerTest.kt
src/test/kotlin/com/fwdekker/randomness/ui/JSpinnerRangeTest.kt
src/test/kotlin/com/fwdekker/randomness/word/WordSettingsComponentTest.kt

* Changes error messages for ranges to say "The minimum length should be larger than ..." rather than "The minimum should be larger than ...".
* Makes word length range error messages easier to read.
* Renames "alphabets" to "symbol sets" in the user interface.
* Adds a test (`testValidRange`) for `JSpinnerRange` that should have been there in the first place.
* Removes "please" from error messages because a) it was done inconsistently, and b) it's more concise.

Improve error messages to refer to components

---

src/main/kotlin/com/fwdekker/randomness/ui/JEditableList.kt
src/test/kotlin/com/fwdekker/randomness/ui/JEditableListTest.kt

When calling `setActiveEntries`, only those entries that are given should be checked afterwards. The old implementation would only check the given entries without considering the state of the other entries.

Fix error where checked entries are not unchecked

---

src/main/java/com/fwdekker/randomness/string/StringSettingsComponent.form
src/main/java/com/fwdekker/randomness/string/StringSettingsComponent.java
src/main/java/com/fwdekker/randomness/uuid/UuidSettingsComponent.form
src/main/java/com/fwdekker/randomness/word/WordSettingsComponent.form
src/main/java/com/fwdekker/randomness/word/WordSettingsComponent.java
src/main/kotlin/com/fwdekker/randomness/ui/JCheckBoxList.kt
src/test/kotlin/com/fwdekker/randomness/string/StringSettingsComponentTest.kt
src/test/kotlin/com/fwdekker/randomness/ui/JCheckBoxListTest.kt
src/test/kotlin/com/fwdekker/randomness/ui/JEditableListTest.kt
src/test/kotlin/com/fwdekker/randomness/word/WordSettingsComponentTest.kt

This PR was unexpectedly complex to write and test.
Fixes #158.
* Renames `JEditableList` to `JCheckBoxList`.
* Adds `JEditableCheckBoxList`; a wrapper around `JCheckBoxList` with the toolbar decorators.
* Fixes a tiny error where the UUID dialog was not large enough during tests on Windows for AssertJ Swing to find the buttons.

Toolbar decorators

---

.config/detekt/.detekt.yml
src/main/java/com/fwdekker/randomness/string/StringSettingsComponent.java
src/main/java/com/fwdekker/randomness/word/WordSettingsComponent.java
src/main/kotlin/com/fwdekker/randomness/ui/JCheckBoxTable.kt
src/test/kotlin/com/fwdekker/randomness/string/StringSettingsComponentTest.kt
src/test/kotlin/com/fwdekker/randomness/ui/JCheckBoxTableTest.kt
src/test/kotlin/com/fwdekker/randomness/word/WordSettingsComponentTest.kt

* Removes the `name` constructor parameter from `JCheckBoxTable`.
* Adds `Column` objects to configure options per column in `JCheckBoxTable`.
* Adds tests for `JCheckBoxTable` and `StringSettingsComponent`.

Re-engineer JCheckBoxTable

---

src/main/java/com/fwdekker/randomness/string/StringSettingsComponent.java
src/main/java/com/fwdekker/randomness/word/WordSettingsComponent.java
src/main/kotlin/com/fwdekker/randomness/SettingsComponent.kt
src/main/kotlin/com/fwdekker/randomness/string/StringSettings.kt
src/main/kotlin/com/fwdekker/randomness/string/SymbolSetTable.kt
src/main/kotlin/com/fwdekker/randomness/word/DictionaryTable.kt
src/main/kotlin/com/fwdekker/randomness/word/WordSettings.kt
src/test/kotlin/com/fwdekker/randomness/string/StringSettingsComponentTest.kt
src/test/kotlin/com/fwdekker/randomness/string/SymbolSetTableTest.kt
src/test/kotlin/com/fwdekker/randomness/word/DictionaryTableTest.kt
src/test/kotlin/com/fwdekker/randomness/word/WordSettingsComponentTest.kt

Fixes #182.
* Adds `@MapAnnotation(sortBeforeSave = false)` to maps of which the order should be retained.
* Adds `isModified(settings: S): Boolean` to detect when duplicates are in a table; this cannot be detected using the original `isModified()` method.
* Moves default lists and maps in `Settings` objects to their respective companion objects.
* Prevents cloning of `BundledDictionary`s by returning a `UserDictionary` instead. There does not seem to be a way to disable the clone button, either permanently or conditionally.

Guarantee entry order

---

src/main/java/com/fwdekker/randomness/string/StringSettingsComponent.java
src/main/java/com/fwdekker/randomness/word/WordSettingsComponent.java
src/main/kotlin/com/fwdekker/randomness/JavaHelper.kt
src/test/kotlin/com/fwdekker/randomness/string/StringSettingsComponentTest.kt
src/test/kotlin/com/fwdekker/randomness/word/WordSettingsComponentTest.kt

* Fixes an issue where the reset and save functions are not available when table entries are reordered but not otherwise edited. This because the `Settings` objects' `equals` methods do not return false if the contents of the sets are reordered.
* Simplifies tests in `WordSettingsComponentTest` by using the `TempFileHelper` where applicable.

Allow reset after reorder

---

README.md

Uses <kbd>\<kbd></kbd> instead of `` ` `` to display keyboard usages in the README.

Use kbd instead of backtick

---

src/main/kotlin/com/fwdekker/randomness/ui/ActivityTableModelEditor.kt
src/main/kotlin/com/fwdekker/randomness/word/DictionaryTable.kt
src/test/kotlin/com/fwdekker/randomness/ui/ActivityTableModelEditorTest.kt

Fixes #185.
It is not possible to get the `TableModelEditor` to remove or conditionally disable the copy button when invoking `createComponent`, so this PR uses reflection to emulate the functionality of that method and adds a custom copy button that _does_ disable the copy button conditionally.
A neater solution would be to get an `isCopyable` method next to the `isRemovable` method. I have opened issue [IJSDK-745](https://youtrack.jetbrains.com/issue/IJSDK-745) on YouTrack to suggest this, but even if it were implemented it would obviously not be available in the older API which this plugin depends on.

Disable copy button conditionally

---

src/main/kotlin/com/fwdekker/randomness/PopupAction.kt
src/main/kotlin/com/fwdekker/randomness/decimal/DecimalActions.kt
src/main/kotlin/com/fwdekker/randomness/integer/IntegerActions.kt
src/main/kotlin/com/fwdekker/randomness/string/StringActions.kt
src/main/kotlin/com/fwdekker/randomness/uuid/UuidActions.kt
src/main/kotlin/com/fwdekker/randomness/word/WordActions.kt
src/main/resources/META-INF/plugin.xml

Fixes #200.
Unlike the issue, this PR only adds the main Randomness action to the menu. Adding all 10 actions (5 normal + 5 array variants) would have been rather messy.
Additionally, this PR
* renames the actions to indicate that they insert _random_ values, and
* adds array insertion actions to the list of actions so that these can be found by searching and can be bound to shortcuts.

Add Randomness to insert menu

---

build.gradle
gradle.properties
src/main/kotlin/com/fwdekker/randomness/uuid/UuidActions.kt
src/main/kotlin/com/fwdekker/randomness/uuid/UuidSettings.kt
src/main/kotlin/com/fwdekker/randomness/uuid/UuidSettingsComponent.form
src/main/kotlin/com/fwdekker/randomness/uuid/UuidSettingsComponent.kt
src/main/resources/randomness.properties
src/test/kotlin/com/fwdekker/randomness/uuid/UuidInsertActionTest.kt
src/test/kotlin/com/fwdekker/randomness/uuid/UuidSettingsComponentTest.kt
src/test/kotlin/com/fwdekker/randomness/uuid/UuidSettingsTest.kt

Fixes #154.
Generating types other than 1 and 4 does not make much sense since these are not random.

Generate other types of UUIDs

---

src/main/kotlin/com/fwdekker/randomness/ui/JBPopupHelper.kt

#230 wasn't the cleanest PR. This PR removes the unnecessary `println`, improves variable names, fixes a bug where pressing numbers didn't actually work, and simplifies the Cartesian product function.

Clean up after #230

---

src/main/kotlin/com/fwdekker/randomness/DataActions.kt
src/main/kotlin/com/fwdekker/randomness/DummyActions.kt
src/main/kotlin/com/fwdekker/randomness/array/ArraySettingsComponent.kt
src/main/kotlin/com/fwdekker/randomness/decimal/DecimalSettingsComponent.kt
src/main/kotlin/com/fwdekker/randomness/integer/IntegerSettingsComponent.kt
src/main/kotlin/com/fwdekker/randomness/string/StringSettingsComponent.kt
src/main/kotlin/com/fwdekker/randomness/ui/PreviewPanel.kt
src/main/kotlin/com/fwdekker/randomness/uuid/UuidSettingsComponent.kt
src/main/kotlin/com/fwdekker/randomness/word/WordSettingsComponent.kt
src/test/kotlin/com/fwdekker/randomness/DataInsertActionIntegrationTest.kt
src/test/kotlin/com/fwdekker/randomness/DataInsertActionTest.kt
src/test/kotlin/com/fwdekker/randomness/array/DataInsertArrayActionTest.kt
src/test/kotlin/com/fwdekker/randomness/ui/PreviewPanelTest.kt

Fixes #240 and fixes #239.
Random values are used for the preview, thus fixing #240. Because these values are random and use the seed, #239 is no longer valid.
Additionally, the generic part of the `PreviewPanel` has been removed because it was not necessary.

Display different values in array preview

---

src/main/kotlin/com/fwdekker/randomness/string/SymbolSetTable.kt
src/main/resources/META-INF/change-notes.html

Implements the `ExpandableTextField` suggestion from #209.

Add expandable text fields for symbol sets

---

src/main/kotlin/com/fwdekker/randomness/array/ArraySettingsComponent.form
src/main/kotlin/com/fwdekker/randomness/decimal/DecimalSettingsComponent.form
src/main/kotlin/com/fwdekker/randomness/integer/IntegerSettings.kt
src/main/kotlin/com/fwdekker/randomness/integer/IntegerSettingsComponent.form
src/main/kotlin/com/fwdekker/randomness/string/StringSettingsComponent.form
src/main/kotlin/com/fwdekker/randomness/ui/PreviewPanel.form
src/main/kotlin/com/fwdekker/randomness/ui/PreviewPanel.kt
src/main/kotlin/com/fwdekker/randomness/uuid/UuidSettingsComponent.form
src/main/kotlin/com/fwdekker/randomness/word/WordSettingsComponent.form
src/main/resources/META-INF/change-notes.html
src/test/kotlin/com/fwdekker/randomness/ui/PreviewPanelTest.kt

Fixes #250.
Additionally, the form files had been accumulating weird garbage from years of usages, so this PR cleans them up a bit. It removes unnecessary columns and reorders some elements in the form so that they closer correspond to what they look like.
PS: And it also fixes a bug where the default integer scheme name was `@` instead of `Default`.

Preview wrapping

---

gradle.properties
src/main/kotlin/com/fwdekker/randomness/ui/ActivityTableModelEditor.kt
src/main/resources/META-INF/change-notes.html
src/main/resources/META-INF/description.html

As per the [update details of v2.4.0](https://plugins.jetbrains.com/plugin/9836-randomness/update/75531), v2.4.0 is incompatible with IntelliJ versions below 191. This PR fixes the incompatible API usage and bumps the version to v2.4.1.

Provide API v181+ compatibility hotfix

---

.github/ISSUE_TEMPLATE/bug_report.md
README.md
build.gradle
gradle/scripts/verifier.gradle

Fixes #261.
The implementation could certainly use some improvement because it must re-download all IDEs to check against if you run `clean`. The [Gradle IntelliJ plugin](https://github.com/JetBrains/gradle-intellij-plugin) uses the Maven cache for this. I don't think it's worthwhile trying to replicate this, so under the assumption that I'll only run this task once before every release I'm fine with it. Perhaps JetBrains/gradle-intellij-plugin#385 will be fixed one day.

Automatic verifier

---

build.gradle
gradle/scripts/verifier.gradle

Improves upon #262 by storing the IDEs in the Gradle cache.

Use Gradle cache for verifier IDEs

---

src/main/kotlin/com/fwdekker/randomness/array/ArraySettingsComponent.form
src/main/kotlin/com/fwdekker/randomness/integer/IntegerSettingsComponent.form
src/main/kotlin/com/fwdekker/randomness/string/StringSettingsComponent.form
src/main/kotlin/com/fwdekker/randomness/ui/PreviewPanel.form
src/main/kotlin/com/fwdekker/randomness/uuid/UuidSettingsComponent.form
src/main/kotlin/com/fwdekker/randomness/word/WordSettingsComponent.form
src/main/resources/META-INF/change-notes.html

Fixes #264. Fixes #265. Fixes #266.
* For some reason many of the GUI forms specified unnecessary preferred sizes for components, forcing them to a certain width even if that didn't make sense. In the words dialog, this caused the panel to be wider than the dialog, making the dictionary table think it had more space to expand into than it actually did.
* In the string dialog, the table wasn't configured to want to grow, and as a result it didn't make optimal use of the vertical space.
* In the preview panel (and thus in all settings dialogs), the textarea automatically changed its minimum width every time the dialog resized. By setting an explicit minimum and preferred width of 0, this behaviour stopped. ([Thanks, Datoraki.](https://stackoverflow.com/a/6022219/))

Fix issues surrounding dialog sizes

---

src/main/kotlin/com/fwdekker/randomness/ui/ActivityTableModelEditor.kt

Fixes #270, with a compromise. Instead of directly opening that cell's editor, the user must press <kbd>Enter</kbd> before they can edit the cell. Editing can be stopped by pressing the <kbd>Esc</kbd> key.

Activity table tab

---

README.md
build.gradle
src/main/kotlin/com/fwdekker/randomness/array/ArraySettingsComponent.form
src/main/kotlin/com/fwdekker/randomness/decimal/DecimalSettingsComponent.form
src/main/kotlin/com/fwdekker/randomness/integer/IntegerSettingsComponent.form
src/main/kotlin/com/fwdekker/randomness/string/StringSettingsComponent.form
src/main/kotlin/com/fwdekker/randomness/word/WordSettingsComponent.form
src/main/resources/META-INF/change-notes.html

Fixes #283 (both checkboxes).
* Reorders the order of radio buttons in the button groups, and
* removes the `labelFor` properties of labels.

Focus order

---

build.gradle
gradle.properties
src/main/kotlin/com/fwdekker/randomness/string/StringActions.kt
src/main/kotlin/com/fwdekker/randomness/string/SymbolSet.kt
src/main/resources/META-INF/change-notes.html
src/test/kotlin/com/fwdekker/randomness/string/StringInsertActionTest.kt
src/test/kotlin/com/fwdekker/randomness/string/SymbolSetTest.kt

Add support for emoji

---

gradle.properties
src/main/kotlin/com/fwdekker/randomness/uuid/UuidActions.kt
src/main/resources/META-INF/change-notes.html

Fixes #282 by using the new custom-clock functionality of v3.3.0 of the UUID generator library.

Ensure time-based UUID previews respect seed

---

src/main/kotlin/com/fwdekker/randomness/ErrorReporter.kt
src/main/resources/META-INF/change-notes.html
src/main/resources/META-INF/plugin.xml

Fixes #293 by allowing users to report fatal errors in Randomness through IntelliJ by binding the report button to open a pre-filled GitHub issue in the browser.

Implement basic error reporter

---

build.gradle
src/main/resources/META-INF/change-notes.html

See title. Reduces plugin distribution size by approx. 4 MB.

Remove Kotlin as implementation dependency

---

build.gradle

Reverts #297; by not bundling Kotlin in the distribution the plugin was no longer compatible with IntelliJ 2018.1 because that version uses Kotlin 1.2 while the distribution was compiled for Kotlin 1.3. I could not find an easy way to compile for Kotlin 1.2 using IntelliJ, so I've decided to continue bundling Kotlin with the distribution.

Revert #297

---

README.md

Fixes #307.
These changes have also been applied to the plugin's general usage instructions on IntelliJ's marketplace.

Clarify what the repeat action does

---

.config/detekt/.detekt.yml
build.gradle
gradle.properties
src/main/kotlin/com/fwdekker/randomness/Settings.kt
src/main/kotlin/com/fwdekker/randomness/array/ArraySettings.kt
src/main/kotlin/com/fwdekker/randomness/decimal/DecimalSettings.kt
src/main/kotlin/com/fwdekker/randomness/integer/IntegerSettings.kt
src/main/kotlin/com/fwdekker/randomness/string/StringSettings.kt
src/main/kotlin/com/fwdekker/randomness/ui/JBPopupHelper.kt
src/main/kotlin/com/fwdekker/randomness/uuid/UuidSettings.kt
src/main/kotlin/com/fwdekker/randomness/word/WordSettings.kt

Fixes #322.
The cause of the bug was that, for some reason, the `@Transient` annotation on the `currentScheme` field was ignored, but only if the build wasn't compiled in debug mode. As a result, the current scheme was serialized into the configuration XML (which isn't really a problem per sé) and when reading it, the call to `schemes.first` would fail because the schemes had not loaded yet.
I still don't know why the annotation was ignored, but changing `first` to `firstOrNull ?: throw Exception` somehow caused the annotation to start working again. Additionally, settings files from previous versions that incorrectly contain the `currentScheme` field will be read without error by this patched version.
---
It took me a long while to figure that out, so I also ended up updating all …

Fix scheme loading/saving (and update dependencies)

---

gradle/wrapper/gradle-wrapper.properties
src/main/kotlin/com/fwdekker/randomness/array/ArraySettings.kt
src/main/kotlin/com/fwdekker/randomness/decimal/DecimalSettings.kt
src/main/kotlin/com/fwdekker/randomness/integer/IntegerSettings.kt
src/main/kotlin/com/fwdekker/randomness/string/StringSettings.kt
src/main/kotlin/com/fwdekker/randomness/uuid/UuidSettings.kt
src/main/kotlin/com/fwdekker/randomness/word/WordSettings.kt
src/main/resources/META-INF/plugin.xml

Fixes #323, i.e. changes the plugin dependency from `com.intellij.modules.lang` to `com.intellij.modules.platform`.
Also, reverts a change made in #324 where `service()` was used, because that function is not compatible with IntelliJ API 181+. 
Finally, updates Gradle to the latest version.

Fix SDK compatibility and update Gradle

---

gradle/scripts/verifier.gradle

Fixes #328.
@PawelLipski, can you confirm that this resolves the issue for you?

Resolve EAP IDEs for plugin verifier

---

src/main/kotlin/com/fwdekker/randomness/ErrorReporter.kt
src/main/resources/META-INF/change-notes.html
src/test/kotlin/com/fwdekker/randomness/ErrorReporterTest.kt

Fixes #330 by trying out various combinations of the available information and choosing the option that fits given the maximum URL length supported by GitHub.
Fixes #335 by truncating ampersands altogether. The `BrowserUtil` currently cannot handle ampersands that are not used to separate query parameters because if they are not escaped they will be treated as query parameters, and if they are escaped with `%26` then the `%` in there will be escaped to `%25` resulting in `%2526` and then a literal `%26` in the input field. Similar issues apply to `#`, `;`, and ` `. Also see [IDEA-244360](https://youtrack.jetbrains.com/issue/IDEA-244360).

Error report fixes

---

src/main/kotlin/com/fwdekker/randomness/integer/IntegerSettings.kt
src/main/kotlin/com/fwdekker/randomness/string/StringSettings.kt
src/main/kotlin/com/fwdekker/randomness/ui/ActivityTableModelEditor.kt
src/main/kotlin/com/fwdekker/randomness/ui/PreviewPanel.kt
src/main/kotlin/com/fwdekker/randomness/word/WordSettingsComponent.form
src/main/kotlin/com/fwdekker/randomness/word/WordSettingsComponent.kt
src/main/resources/META-INF/change-notes.html
src/main/resources/randomness.properties

Fixes #347.
Also slightly improves the appearance of the preview text by removing the border and making it unselectable.

Add dictionary help information to settings

---

src/main/kotlin/com/fwdekker/randomness/word/DictionaryTable.kt
src/main/resources/META-INF/change-notes.html

Fixes #350.
Implementing advanced drag and drop (e.g. drag files to table, files are then added as user dictionaries) was not possible because the IntelliJ classes do not support adding a custom `TransferHandler`. This would require hacking deeply into `ToolbarDecorator`, which does not seem feasible or at all stable. Instead, the only change introduced by this PR is that when a file is dragged onto the location editor, the `file://` at the start that may appear is removed. This slightly improves DnD support, but more advanced features were not possible.

Improve dictionary table support for drag and drop

---

build.gradle
src/main/resources/META-INF/plugin.xml
src/test/kotlin/com/fwdekker/randomness/word/DictionaryTest.kt

Updates minimum IDE version from 193 to 201. This is because the plugin verifier detected that `.children` in `RandomConfigurable` does not work in build 193 when compiled for 203 (even though it works for 193 when compiled for 193) and because some `label` functions using the Kotlin UI DSL in `RandomConfigurable` also didn't work.
Additionally, this PR
* disables a few tests on Windows machines that do not work there,
* adds more IDE versions to check for the compatibility verifier,
* and clarifies the build compatibility rule from #209 with a line in `build.gradle`.

Bump IDE dependency to build 201

---

src/main/kotlin/com/fwdekker/randomness/decimal/DecimalSettingsComponent.kt
src/main/kotlin/com/fwdekker/randomness/integer/IntegerActions.kt
src/main/kotlin/com/fwdekker/randomness/ui/JSpinnerRange.kt
src/test/kotlin/com/fwdekker/randomness/integer/IntegerInsertActionTest.kt
src/test/kotlin/com/fwdekker/randomness/ui/JSpinnerRangeTest.kt

Adds a simple wrapper `randomLong` around `random.nextLong` that generates a random number in an inclusive range, regardless of the range between the `from` and `until`.
Removes the need for a maximum value range in integer settings.
Fixes #367 and fixes #370.

Add randomLong function to prevent overflows

---

build.gradle.kts
gradle.properties
src/main/kotlin/com/fwdekker/randomness/DataActions.kt
src/main/kotlin/com/fwdekker/randomness/array/ArraySettingsComponent.kt
src/main/kotlin/com/fwdekker/randomness/decimal/DecimalActions.kt
src/main/kotlin/com/fwdekker/randomness/integer/IntegerActions.kt
src/main/kotlin/com/fwdekker/randomness/string/StringActions.kt
src/main/kotlin/com/fwdekker/randomness/string/SymbolSet.kt
src/main/kotlin/com/fwdekker/randomness/ui/PreviewPanel.kt
src/main/kotlin/com/fwdekker/randomness/uuid/UuidActions.kt
src/main/kotlin/com/fwdekker/randomness/word/WordActions.kt
src/main/resources/META-INF/change-notes.html
src/test/kotlin/com/fwdekker/randomness/DataInsertActionTest.kt
src/test/kotlin/com/fwdekker/randomness/string/StringInsertActionTest.kt
src/test/kotlin/com/fwdekker/randomness/string/SymbolSetTest.kt

Fixes #373.
I also fixed a warning about a mismatch between Kotlin 1.4 and 1.5, which was an important one because otherwise the compiled code wouldn't have run on IDEs that have Kotlin 1.4 bundled instead of the desired 1.3.
This PR also majorly improves the speed of generating strings, because it combines the symbol sets before it generates the characters instead of re-calculating it for each character; and then it re-uses the combined set for each string to be generated. 10 strings of length 99,999 are now generated almost instantly; before this PR this took several seconds. Additionally, it removes a step where all emoji were parsed to a string and then separated back into a list; now it just keeps them in the initial list form.
This PR also shifts around a bit of error checking in …

Add timeout for generating values

---

LICENSE
README.md
gradle.properties
src/main/kotlin/com/fwdekker/randomness/string/StringSettings.kt
src/main/resources/META-INF/change-notes.html
src/main/resources/META-INF/plugin.xml
src/test/kotlin/com/fwdekker/randomness/string/StringInsertActionTest.kt
src/test/kotlin/com/fwdekker/randomness/string/StringSettingsTest.kt
src/test/kotlin/com/fwdekker/randomness/string/SymbolSetTableTest.kt
src/test/kotlin/com/fwdekker/randomness/ui/ActivityTableModelEditorTest.kt
src/test/kotlin/com/fwdekker/randomness/ui/PreviewPanelTest.kt
src/test/kotlin/com/fwdekker/randomness/word/DictionaryTableTest.kt

Fixes #382.
The issue was that I had added `serializedSymbolSets` and `serializedActiveSymbolSets` as variants of `symbolSets` and `activeSymbolSets` to ensure that emoji would not get lost when saving preferences. I then set the other variants of this field to be transient, but instead of making them abstractions over the serialized fields, I made them into separate fields. The result was that changes were stored only in the transient fields, but not the fields that were actually written to the preferences file.

Prevent symbol set setting truncation

---

gradle.properties
src/main/kotlin/com/fwdekker/randomness/DataActions.kt
src/main/kotlin/com/fwdekker/randomness/PopupAction.kt
src/main/resources/META-INF/change-notes.html

Fixes #358.
With the release of 2021.2, Randomness can now move minimum support to 2020.3. That means that JDK 8 is no longer required for any of the supported IDEs, so support can be dropped.
No further dependencies were updated, because I don't really see the need to and the uds branch is where all that stuff is happening anyway.

Drop support for Java 8, fix modifier checks

---

src/main/kotlin/com/fwdekker/randomness/StateEditor.kt
src/main/kotlin/com/fwdekker/randomness/array/ArraySchemeDecoratorEditor.kt
src/main/kotlin/com/fwdekker/randomness/decimal/DecimalSchemeEditor.kt
src/main/kotlin/com/fwdekker/randomness/integer/IntegerSchemeEditor.kt
src/main/kotlin/com/fwdekker/randomness/literal/LiteralSchemeEditor.kt
src/main/kotlin/com/fwdekker/randomness/string/StringSchemeEditor.kt
src/main/kotlin/com/fwdekker/randomness/template/TemplateListEditor.kt
src/main/kotlin/com/fwdekker/randomness/template/TemplateNameEditor.kt
src/main/kotlin/com/fwdekker/randomness/template/TemplateReferenceEditor.kt
src/main/kotlin/com/fwdekker/randomness/ui/ButtonGroup.kt
src/main/kotlin/com/fwdekker/randomness/ui/JNumberSpinners.kt
src/main/kotlin/com/fwdekker/randomness/uuid/UuidSchemeEditor.kt
src/main/kotlin/com/fwdekker/randomness/word/WordSchemeEditor.kt

Fixes #357.
Apparently it suffices to request focus in a `SwingUtilities.invokeLater`. However, to ensure that users who just happen to scroll by Randomness settings don't get forced into the editor, the focus is only applied when the dialog is opened from the popup.

Implement default focus after opening settings

---

.github/workflows/ci.yml

Makes it behave the same as before migrating to GitHub Actions. This is quite essential to make the integration, well, continuous.

Run CI on all pushes to all branches

---

src/main/kotlin/com/fwdekker/randomness/SettingsState.kt
src/main/kotlin/com/fwdekker/randomness/template/TemplateListEditor.kt
src/main/kotlin/com/fwdekker/randomness/template/TemplateTree.kt
src/main/kotlin/com/fwdekker/randomness/ui/ListenerHelper.kt
src/test/kotlin/com/fwdekker/randomness/Dummies.kt
src/test/kotlin/com/fwdekker/randomness/SettingsStateTest.kt
src/test/kotlin/com/fwdekker/randomness/template/TemplateListEditorTest.kt
src/test/kotlin/com/fwdekker/randomness/template/TemplateListTest.kt
src/test/kotlin/com/fwdekker/randomness/template/TemplateTest.kt
src/test/kotlin/com/fwdekker/randomness/template/TemplateTreeTest.kt

Splits off the part of `TemplateListEditor` that is about showing a tree of templates and moves it into its own class `TemplateTree`, and tests it.

Split template tree

---

src/main/kotlin/com/fwdekker/randomness/template/TemplateJTree.kt
src/main/kotlin/com/fwdekker/randomness/template/TemplateListEditor.kt
src/main/kotlin/com/fwdekker/randomness/template/TemplateSettings.kt
src/main/kotlin/com/fwdekker/randomness/template/TemplateTree.kt
src/main/kotlin/com/fwdekker/randomness/ui/ActivityTableModelEditor.kt
src/main/kotlin/com/fwdekker/randomness/ui/ListenerHelper.kt
src/main/kotlin/com/fwdekker/randomness/ui/PreviewPanel.kt
src/main/kotlin/com/fwdekker/randomness/word/DictionaryTable.kt
src/test/kotlin/com/fwdekker/randomness/template/TemplateListEditorTest.kt
src/test/kotlin/com/fwdekker/randomness/template/TemplateTreeTest.kt
src/test/kotlin/com/fwdekker/randomness/ui/ListenerHelperTest.kt
src/test/kotlin/com/fwdekker/randomness/ui/PreviewPanelTest.kt

Contains several important QoL/UX improvements, such as:
* Copying/adding a template will give it a unique name to prevent conflicts, so that you can immediately save.
* After pressing reset, the previously-selected scheme remains selected.
* Speed search in template list
* Added shortcuts to template list buttons
* Template editor splitter ratio is now persistent
* Fixed old bug where bundled dictionaries could always be edited
* Button to add scheme to template list now changes behaviour depending on current selection, and is not flat to make it quicker to select a scheme to add, and supports fast searching
* Preview can now be refreshed from keyboard

UX improvements

---

src/main/kotlin/com/fwdekker/randomness/ErrorReporter.kt
src/main/resources/randomness.properties
src/test/kotlin/com/fwdekker/randomness/ErrorReporterTest.kt

Fixes #411.
Looking at their code, perhaps I was mistaken that TeXiFy doesn't include stacktraces. But either way I've always felt that my code was very finnicky and I fear that the error reporter sometimes breaks, which is of course not a good thing. So to be on the safe side, the error reporter is now much less complex and simply asks the user to copy the stacktrace into GitHub. A bit more work for the user, but I think it's less prone to crashing this way.
If GitHub had a better way of doing this I would have used it, but I can't really imagine how that would work without authentication.

Simplify error reporter

---

src/main/kotlin/com/fwdekker/randomness/array/ArrayDecoratorEditor.kt
src/main/kotlin/com/fwdekker/randomness/decimal/DecimalSchemeEditor.kt
src/main/kotlin/com/fwdekker/randomness/fixedlength/FixedLengthDecoratorEditor.kt
src/main/kotlin/com/fwdekker/randomness/integer/IntegerSchemeEditor.kt
src/main/kotlin/com/fwdekker/randomness/ui/JNumberSpinners.kt
src/main/kotlin/com/fwdekker/randomness/ui/VariableLabelRadioButton.kt
src/test/kotlin/com/fwdekker/randomness/array/ArrayDecoratorEditorTest.kt
src/test/kotlin/com/fwdekker/randomness/ui/VariableLabelRadioButtonTest.kt

* Resolves an issue where `JDoubleSpinner`s took up extremely excessive width in the decimal settings.
* Disables variable label inputs if not currently selected, to make `tab`-based navigation easier. This also fixes a bug where selecting tab would not only focus but also select the variable label input.
* A little bit of code quality here and there.

Some fixes

---

packages.md
src/main/kotlin/com/fwdekker/randomness/template/TemplateListEditor.kt
src/main/kotlin/com/fwdekker/randomness/ui/PreviewPanel.kt
src/main/kotlin/com/fwdekker/randomness/word/DefaultWordList.kt
src/main/kotlin/com/fwdekker/randomness/word/WordSchemeEditor.form
src/main/kotlin/com/fwdekker/randomness/word/WordSchemeEditor.kt
src/main/resources/randomness.properties
src/main/resources/word-lists/names.txt
src/main/resources/word-lists/places.txt
src/test/kotlin/com/fwdekker/randomness/word/DefaultWordListTest.kt
src/test/kotlin/com/fwdekker/randomness/word/WordSchemeEditorTest.kt
src/test/resources/word-lists/non-empty-list.txt
src/test/resources/word-lists/timing-test-global.txt
src/test/resources/word-lists/timing-test-instance.txt
src/test/resources/word-lists/with-blank-lines.txt

Sort-of re-introduces the "dictionary" in the sense that users can select from a pre-defined list of word lists to paste into their word list editor. As before, word lists are cached appropriately. Currently, the available word lists are just placeholders.
Also
* disables undo actions for the preview, as this would cause exceptions when pressing Ctrl+Z while looking at the preview,
* adds newlines at the end of loaded word lists, and
* resolves an issue where editors would get disposed multiple times.

Preset word list

---

src/main/kotlin/com/fwdekker/randomness/BracketsDescriptor.kt
src/main/kotlin/com/fwdekker/randomness/array/ArrayDecorator.kt
src/main/kotlin/com/fwdekker/randomness/string/StringSchemeEditor.kt
src/main/resources/randomness.properties
src/test/kotlin/com/fwdekker/randomness/BracketsDescriptorTest.kt
src/test/kotlin/com/fwdekker/randomness/array/ArrayDecoratorTest.kt

When providing custom brackets for an array, the user can now escape the `@` with a `\` (and escape a `\` with `\\`). This is achieved with the `BracketsDescriptor` class. The UI tooltip has been updated accordingly.

Escape at in custom list

---

.github/workflows/ci.yml

Some of the dependencies of the GitHub CI action were a bit outdated, resulting in deprecation warnings in the build logs. I have bumped them to the next version. I'm mostly sure it should all still work.

Update CI action dependencies

---

CHANGELOG.md
gradle.properties
src/main/kotlin/com/fwdekker/randomness/Settings.kt
src/main/kotlin/com/fwdekker/randomness/XmlHelpers.kt
src/test/kotlin/com/fwdekker/randomness/SettingsTest.kt
src/test/kotlin/com/fwdekker/randomness/XmlHelpersTest.kt
src/test/kotlin/com/fwdekker/randomness/template/TemplateJTreeTest.kt
src/test/kotlin/com/fwdekker/randomness/template/TemplateListEditorTest.kt
src/test/kotlin/com/fwdekker/randomness/template/TemplateReferenceEditorTest.kt
src/test/kotlin/com/fwdekker/randomness/template/TemplateReferenceTest.kt

Fixes #464.
Stores the plugin's version in the user's settings to allow version detection in the future. Furthermore, though `Settings` remains the usual object with a `templateList` (and perhaps other fields in the future (cf. #469?)), the class `PersistentSettings` now acts as if settings are saved as an `Element` (i.e. as XML). When settings are loaded, `PersistentSettings` has the opportunity to modify the XML before deserialising it into a `Settings`. Therefore, if there are incompatibilities between versions that the default XML deserialiser cannot handle, a small bit of code can be added to make these modifications automatically.

Add framework for settings backwards compatibility

---

.github/workflows/ci.yml
CHANGELOG.md

Fixes #502.
Adds tests on macOS, upgrades various actions, uses new actions where appropriate, and uploads coverage only once all tests have passed.

Rewrite CI scripts

---

.config/dokka/logo-icon.svg
.github/SECURITY.md
.github/workflows/cd.yml
build.gradle.kts
gradle.properties
gradle/wrapper/gradle-wrapper.properties
src/main/kotlin/com/fwdekker/randomness/Settings.kt

Modernises the Dokka setup:
* Adds a version dropdown menu to switch between versions.
* Adds a workflow that will update the GitHub pages automatically when a new GitHub release is created.
* Adds an icon and favicon to the documentation.
* Fixes a bug where the version number is displayed multiple times in the header.
* Shows documentation for all functions, not just public functions. (I think I've "fixed" this bug multiple times over the years...)
In the process, I also discovered and reported Kotlin/dokka#3398.
Also, rewrites the security policy. The most relevant change here is that vulnerabilities should preferably [be reported through GitHub's reporting system](https://github.com/FWDekker/intellij-randomness/security/advisories/new) instead of mailing it to a private email address. …

Modern Dokka

---

CHANGELOG.md
src/main/kotlin/com/fwdekker/randomness/array/ArrayDecorator.kt
src/test/kotlin/com/fwdekker/randomness/array/ArrayDecoratorTest.kt

Vary number of array elements per caret

---

.github/workflows/cd.yml
build.gradle.kts

Provides a workaround for Kotlin/dokka#3398 by adding a finalizing task to `dokkaHtml` that (1) removes excessive newlines, and (2) removes `.git` and `.idea` directories which are copied by Dokka.

Clean Dokka output with Gradle task

---

src/main/kotlin/com/fwdekker/randomness/array/ArrayDecoratorEditor.kt
src/main/kotlin/com/fwdekker/randomness/template/TemplateListConfigurable.kt
src/main/kotlin/com/fwdekker/randomness/template/TemplateListEditor.kt
src/main/kotlin/com/fwdekker/randomness/template/TemplateReferenceEditor.kt
src/main/kotlin/com/fwdekker/randomness/ui/InterfaceBuilderHelpers.kt
src/main/resources/randomness.properties

Fixes #495.
Also improves a little bit of code quality here and there.

Add button to jump to reference's target template

---

src/main/resources/META-INF/plugin.xml

Instead of fixing #520, this just disables the dynamic reloading feature.
I spent more than 6 hours trying to find out why dynamic reloading didn't work, found a bunch of supposed memory leaks, and then found extremely insufficient documentation on JetBrains' end on alternative design patterns to avoid those leaks. (Apparently every single `Companion` object was still referenced by the classloader. How am I supposed to avoid _that_?)
It's not worth my time. By explicitly disabling dynamic reloading, at least users won't see their IDE trying and failing to dynamically reload the plugin.

Disable dynamic plugin reloading

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/SECURITY.md
CHANGELOG.md
build.gradle.kts
gradle.properties
src/main/kotlin/com/fwdekker/randomness/ErrorReporter.kt
src/main/kotlin/com/fwdekker/randomness/Icons.kt
src/main/kotlin/com/fwdekker/randomness/InsertAction.kt
src/main/kotlin/com/fwdekker/randomness/Notifier.kt
src/main/kotlin/com/fwdekker/randomness/Settings.kt
src/main/kotlin/com/fwdekker/randomness/Timely.kt
src/main/kotlin/com/fwdekker/randomness/string/StringScheme.kt
src/main/kotlin/com/fwdekker/randomness/template/TemplateActionLoader.kt
src/main/kotlin/com/fwdekker/randomness/template/TemplateListConfigurable.kt
src/main/resources/META-INF/plugin.xml
src/main/resources/randomness.properties
src/test/kotlin/com/fwdekker/randomness/TimelyTest.kt
src/test/kotlin/com/fwdekker/randomness/testhelpers/AssertJSwingProperties.kt

Inspections fixes

---

CHANGELOG.md
src/main/kotlin/com/fwdekker/randomness/string/StringScheme.kt
src/test/kotlin/com/fwdekker/randomness/string/StringSchemeTest.kt

Fixes FWDekkerBot/intellij-randomness-issues#2.

Fix exception for string patterns such as `[]{1,3}`

---

.gitignore
build.gradle.kts
gradle.properties
src/main/kotlin/com/fwdekker/randomness/Settings.kt
src/main/kotlin/com/fwdekker/randomness/uuid/UuidScheme.kt
src/test/kotlin/com/fwdekker/randomness/template/TemplateJTreeTest.kt

Updates Kotlin to the new K2 compiler, updates the IntelliJ plugin to the new v2, updates a bunch of smaller dependencies, bumps the compatible IntelliJ version, and does some minor cleanup in build scripts.

Update Kotlin to K2, and other dependencies

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/RELEASE_CHECKLIST.md
.github/SECURITY.md
.github/workflows/cd.yml
.github/workflows/ci.yml
CHANGELOG.md
README.md

All the details you need are in the commit messages already, to be honest.

Update docs, prepare for v3.3.2

---

CHANGELOG.md
src/main/kotlin/com/fwdekker/randomness/Icons.kt
src/test/kotlin/com/fwdekker/randomness/IconsTest.kt

Hopefully fixes the recurring "Must be not computed before that call" issue.
Also changes the radial colour arrangement of schemes in template icons to be less mathematical and more intuitive: Clockwise starting from the top instead of counter-clockwise starting from the right.
See also: FWDekkerBot/intellij-randomness-issues#1, FWDekkerBot/intellij-randomness-issues#13, and [IJPL-163887](https://youtrack.jetbrains.com/issue/IJPL-163887/).

Hopefully fix "Must be not computed before that call" issue

---

CHANGELOG.md
README.md
src/main/kotlin/com/fwdekker/randomness/Scheme.kt
src/main/kotlin/com/fwdekker/randomness/affix/AffixDecorator.kt
src/main/kotlin/com/fwdekker/randomness/array/ArrayDecorator.kt
src/main/kotlin/com/fwdekker/randomness/datetime/DateTimeScheme.kt
src/main/kotlin/com/fwdekker/randomness/decimal/DecimalScheme.kt
src/main/kotlin/com/fwdekker/randomness/integer/IntegerScheme.kt
src/main/kotlin/com/fwdekker/randomness/string/StringScheme.kt
src/main/kotlin/com/fwdekker/randomness/template/Template.kt
src/main/kotlin/com/fwdekker/randomness/template/TemplateReference.kt
src/main/kotlin/com/fwdekker/randomness/uuid/UuidScheme.kt
src/main/kotlin/com/fwdekker/randomness/word/WordScheme.kt
src/test/kotlin/com/fwdekker/randomness/StateTestFactory.kt
src/test/kotlin/com/fwdekker/randomness/affix/AffixDecoratorTest.kt
src/test/kotlin/com/fwdekker/randomness/array/ArrayDecoratorTest.kt
src/test/kotlin/com/fwdekker/randomness/datetime/DateTimeSchemeTest.kt
src/test/kotlin/com/fwdekker/randomness/decimal/DecimalSchemeTest.kt
src/test/kotlin/com/fwdekker/randomness/fixedlength/FixedLengthDecoratorTest.kt
src/test/kotlin/com/fwdekker/randomness/integer/IntegerSchemeTest.kt
src/test/kotlin/com/fwdekker/randomness/string/StringSchemeTest.kt
src/test/kotlin/com/fwdekker/randomness/template/TemplateReferenceTest.kt
src/test/kotlin/com/fwdekker/randomness/template/TemplateTest.kt
src/test/kotlin/com/fwdekker/randomness/uuid/UuidSchemeTest.kt
src/test/kotlin/com/fwdekker/randomness/word/WordSchemeTest.kt

Ensure decorator settings are stored

---

CHANGELOG.md
gradle.properties
src/main/kotlin/com/fwdekker/randomness/CapitalizationMode.kt
src/main/kotlin/com/fwdekker/randomness/ListHelpers.kt
src/main/kotlin/com/fwdekker/randomness/PopupAction.kt
src/main/kotlin/com/fwdekker/randomness/Scheme.kt
src/main/kotlin/com/fwdekker/randomness/Settings.kt
src/main/kotlin/com/fwdekker/randomness/State.kt
src/main/kotlin/com/fwdekker/randomness/XmlHelpers.kt
src/main/kotlin/com/fwdekker/randomness/affix/AffixDecoratorEditor.kt
src/main/kotlin/com/fwdekker/randomness/integer/IntegerScheme.kt
src/main/kotlin/com/fwdekker/randomness/template/TemplateReference.kt
src/main/kotlin/com/fwdekker/randomness/uuid/UuidScheme.kt
src/main/kotlin/com/fwdekker/randomness/word/WordScheme.kt
src/test/kotlin/com/fwdekker/randomness/CapitalizationModeTest.kt
src/test/kotlin/com/fwdekker/randomness/ListHelpersTest.kt
src/test/kotlin/com/fwdekker/randomness/PersistentSettingsTest.kt
src/test/kotlin/com/fwdekker/randomness/StateReflection.kt
src/test/kotlin/com/fwdekker/randomness/StateReflectionTest.kt
src/test/kotlin/com/fwdekker/randomness/StateTestFactory.kt
src/test/kotlin/com/fwdekker/randomness/XmlHelpersTest.kt
src/test/resources/settings-upgrades/v3.1.0-v3.3.5.xml
src/test/resources/settings-upgrades/v3.3.4-v3.3.5.xml

Fixes issue [#R37](https://github.com/FWDekkerBot/intellij-randomness-issues/issues/37).
The issue was that the `generator` field was incorrectly not seen as transient, and therefore serialized to users' config files. However, a lambda cannot be (de)serialized! Therefore, when loading the config, an exception occurred.
Understanding how the serializer determines what to serialize was very tough. It's so tough, and so unclear (imo) that I decided to [open an issue with JetBrains](https://youtrack.jetbrains.com/issue/IJPL-175868/Unclear-Transient-behaviour-with-inheritance) requesting that they either make it work as I expect it to, or better document how it works currently.
Until then, I have added a large number of tests that help verifying that serialization is successful. Previously, …

Fix and verify property transience

---

CHANGELOG.md
gradle.properties
src/main/kotlin/com/fwdekker/randomness/ErrorReporter.kt
src/main/kotlin/com/fwdekker/randomness/Settings.kt
src/main/resources/randomness.properties

Fixes FWDekkerBot/intellij-randomness-issues#40.
Simply makes sure that the initialisation of the network-related code happens inside the `GithubReporter`'s `try`-`catch` block.

Fix bug reporter bug, prepare for v3.3.6

---

src/main/kotlin/com/fwdekker/randomness/Icons.kt
src/test/kotlin/com/fwdekker/randomness/IconsTest.kt

(Hopefully) fixes regression FWDekkerBot/intellij-randomness-issues#44, which was introduced in v3.4.0 when the icons were overhauled, and I forgot about the "don't access icon proprties during the constructor" part. Or rather, I had only half-remembered that, and applied that knowledge to the icon that was returned, but didn't remember that for the input icons.
Either way, this _should_ resolve that regression, and additionally adds documentation to the code to prevent such mistakes in the future. I would have preferred writing tests that detect such mistakes in the future, but I can't even find a way to manually or programmatically reproduce the issue on my end to begin with.

Defer icon validation again
